### ISSUE TITLE
Web interface to integrate file navigation with classification

### ISSUE THREAD

**Issue by jkitzes** [kitzeslab/opensoundscape#10]
In the long term, we might consider whether we could integrate something from [Pumilio](https://github.com/ljvillanueva/pumilio) or something similar.

**Comment by chiroptical** [comment]
Pumilio is no longer maintained: https://github.com/ljvillanueva/pumilio#important-note

@jkitzes is it worth keeping this open?

**Comment by jkitzes** [comment]
We can close, more here for potential future inspiration than as a to-do.
