### ISSUE TITLE
Add a generate_embeddings() method to custom CNN

### ISSUE THREAD

**Issue by Maxime-Bru** [kitzeslab/opensoundscape#1056]
I trained a custom CNN model following the tutorial (https://opensoundscape.org/en/latest/tutorials/train_cnn.html).

Now my model has a predict() method to get the prediction scores. I don't think it is yet possible to retrieve the embeddings: would it be possible to add a generate_embeddings() method to achieve this?

**Comment by sammlapp** [comment]
Hi @Maxime-Bru , this feature is implemented in the `develop` branch as `CNN.embed()` and will be included in the upcoming 0.11.0 release. To accomplish something similar in current/previous releases follow [this example](https://github.com/kitzeslab/bioacoustics-cookbook/blob/main/cnn_embed.ipynb) from the cookbook.

**Comment by Maxime-Bru** [comment]
Thank you, this works perfectly!
