### ISSUE TITLE
Install fails with Python 3.12.3

### ISSUE THREAD

**Issue by jhuus** [kitzeslab/opensoundscape#1059]
I typed "pip install opensoundscape==0.10.2" and got a series of error messages saying "Requires-Python >=3.7.1,<3.10". I'm using the latest Ubuntu which comes with Python 3.12.3 by default. Can opensoundscape be updated to support Python 3.12.3?

**Comment by sammlapp** [comment]
Hi Jan, I just checked and our test suite is passing for Python 3.12 on the develop branch. So I've modified the requirements to allow python 3.9-3.12. These changes will be included in the upcoming 0.11.0 release. 

In the meantime, for opensoundscape 0.10.x, we recommend choosing Python 3.10 when you create an environment, e.g. `conda create -n opso python=3.10`. You're also welcome to install the `develop` branch for the latest features and Python 3.12 support.

**Comment by jhuus** [comment]
Thanks Sam. I’ll try that out on the weekend.

Jan
