### ISSUE TITLE
Expand active learning capabilities

### ISSUE THREAD

**Issue by jkitzes** [kitzeslab/opensoundscape#11]
The high cross-correlation script is a simple form of active learning, in which we try to intelligently target the choice of additional files to annotate. In that case, we're just looking to add more templates. In a finer formulation, we'd be looking to manually annotate somehow ambiguous cases to more generally improve classifier accuracy. We might review DOI: 10.1111/2041-210X.13042 for some active learning implementation ideas.

**Comment by chiroptical** [comment]
@jkitzes I don't think this is still relevant?

**Comment by jkitzes** [comment]
It's relevant, but not to OpSo development - so we can close.
