### ISSUE TITLE
Audio(path) does not fail

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#146]
using the Audio constructor on a file path should fail, but it returns an Audio object with a very short length.

**Comment by chiroptical** [comment]
@sammlapp Could you elaborate on this? The constructor,

https://github.com/kitzeslab/opensoundscape/blob/develop/opensoundscape/audio.py#L32-L34

should require you to input `samples` and `sample_rate`

**Comment by sammlapp** [comment]
whoops didn't see your reply. I called the constructor like Audio("path/to/file",48000) and it returned a very short Audio object, presumably based on the contents of the file path string.
