### ISSUE TITLE
Model distribution enhancement

### ISSUE THREAD

**Issue by rhine3** [kitzeslab/opensoundscape#159]
Could distribute model state dictionaries with metadata, e.g.:
- state dictionary of model itself
- data that the model was trained on and an ordered list of the names of the classes predicted
- model structure (e.g. resnet version, linear classifier specifications) specified as strings/json/etc
- which "switches were turned on" to train the model, i.e. whether augmentation, upsampling, etc. were used
- version of OpenSoundscape used to train the model
- that model's performance metrics on a (versioned) dataset

**Comment by rhine3** [comment]
Another option: store all models generated with one pipeline together inside a single folder, with one metadata file. Besides the state dictionary, all of the data described above should be the same for one set of procedurally generated models.

**Comment by sammlapp** [comment]
model saving now saves the entire object which retains all of the desired information.
