### ISSUE TITLE
This will not actually run on GPUs this way

### ISSUE THREAD

**Issue by chiroptical** [kitzeslab/opensoundscape#160]
https://github.com/kitzeslab/opensoundscape/blob/1316ae35fbf84f5507275d6c32b85fffb9f341a8/opensoundscape/torch/train.py#L51

If you try to run this on the GPU you will get an error. For now, I needed to modify `CUDA_VISIBLE_DEVICES=""` to work around it.

**Comment by rhine3** [comment]
Some CUDA-related notes regarding augmentations:

Some GPU-using augmentations (`opensoundscape.torch.spec_aug`) are called inside of the training function. But other non-tensor augmentations are in the Dataset currently named `BinaryFromAudio` (likely to be renamed to `SingleTargetAudioDataset`). It would be preferable to put all of the augmentations in one place, e.g. in the `__getitem__` of the Dataset, though #157 suggests we could also put augmentations inside the train function as well. 

Putting all augmentations in `__getitem__` would require at least these two performance improvements:

1. explicitly giving `__getitem__` access to GPU
2. avoiding copying data from CPU to the GPU twice (once in the loader, once in the block). May be possible to pass CUDA tensors from a dataloader.

**Comment by chiroptical** [comment]
Should be fixed in #201 

Regarding the other comments. I don't think the `tensor_augment` stuff will make sense in the `Dataset` as much as it would be nice. The augmentation will be so much more performant on the GPU.

**Comment by rhine3** [comment]
Agreed -- `tensor_augment` can stay in the train function for now.
