### ISSUE TITLE
add spec augmentation in Dataset creation

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#164]
It seems that the spec_augment option of datasets.BinaryFromAudio (soon to be renamed) does not perform the augmentation. Maybe this just hasn't been done yet?

if self.spec_augment:
            X = X[0].unsqueeze(0)

**Comment by sammlapp** [comment]
also I think the "add_noise" stuff should be a part of spec_augment (right?)

**Comment by chiroptical** [comment]
I think this is no longer relevant. The `tensor_augment` stuff is put directly into the training loop. The addition of noise is now handled by: https://github.com/kitzeslab/opensoundscape/blob/master/opensoundscape/datasets.py#L262-L275
