### ISSUE TITLE
Make workaround for single-channel bug in RandomAffine

### ISSUE THREAD

**Issue by rhine3** [kitzeslab/opensoundscape#182]
We use RandomAffine as one of the `add_noise` transforms in the audio dataset creator ([see here](https://github.com/kitzeslab/opensoundscape/blob/develop/opensoundscape/datasets.py#L235)). However, we find that this transformation only applies RandomAffine in one channel of a 3-channel (RGB) image. To fix, we will either have to apply the RandomAffine transformation to each channel individually, or apply to channel 0 then duplicate channel 0 three times.

**Comment by rhine3** [comment]
From @chiroptical:
> We use `fillcolor=50` which changes the color of the blank spots to (50, 0, 0) which is why the latter two channels are equal. If you choose `fillcolor=(50, 50, 50)` they will all be equal

**Comment by chiroptical** [comment]
Fixed by #203
