### ISSUE TITLE
function does 2 conceptually separate things

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#183]
I think that splitting data into train/validation should be one operation, and creating numeric labels should be a separate one. I don't think we currently have any functions that generate numeric labels for multi-class training. 
https://github.com/kitzeslab/opensoundscape/blob/4136bb2e1187fce9fe7766ef8636151646820e47/opensoundscape/data_selection.py#L29-L63

**Comment by rhine3** [comment]
I like the idea of separating these. The function that converts a string-labeled dataframe into a numerically labeled dataframe can also output the dictionary of translations from numeric labels to string labels, to then be saved in future `Dataset`s and model outputs

**Comment by chiroptical** [comment]
Fixed in #234
