### ISSUE TITLE
Black precommit hook is no longer in place?

### ISSUE THREAD

**Issue by chiroptical** [kitzeslab/opensoundscape#184]
I have seen some "apply black formatter" commits as well as failed runs. We should probably make sure the precommit hook is in place and working for everyone.

**Comment by chiroptical** [comment]
Add some documentation in #204 but users need to run `poetry run pre-commit install` for it to work

**Comment by rhine3** [comment]
Correct me if I'm wrong, but I think that for now this is fixed to the best of our ability; contributors will just have to remember to run this command
