### ISSUE TITLE
Updates to splitting code

### ISSUE THREAD

**Issue by rhine3** [kitzeslab/opensoundscape#185]
Fixing some bugs and adding some enhancements to the splitting functionality:

1. Currently the splitting code generates random strings for its output filenames. It would be better to produce human-interpretable outputs showing the origin file and the time range of the split, e.g. `mylongfile_0.0s-6.0s.wav`. If this poses too much of a risk of overwriting already-split files, we could append a random string to the end of the filename.

2. It would be good to have a helper function for `SplitterDataset` that implements the current console script so splitting functionality can easily be called from Python

https://github.com/kitzeslab/opensoundscape/blob/5b9d66c9c4e448c988184ae7f81d781681cc55ed/opensoundscape/console.py#L89-L132

3. We should add some additional Raven annotation file splitting functionality + tests. Ideally there would be two options when presented with a Raven selection file: (1) extracting segments from Raven files, or (2) splitting files sequentially, agnostic of Raven annotations, and producing an output file that gives the corresponding Raven labels of all species in each split file, including files where there were no labels. Testing this code recently I was only able to do (1)--or else the functionality for (2) is broken, because `results.csv` included a label for every split, when many splits should have been labeled as "absent."  These changes should also include tests of CSV output formats.

**Comment by rhine3** [comment]
RE: conversation with @chiroptical:

1. is addressed by #199 

2. is also addressed by #199 but we still need to reimplement the CLI using the new function

3. The current implementation of (1) is to split files agnostic of Raven labels, then only save the ones that are Raven-labeled. To implement (2) we will have to add a flag to `SplitterDataset` to write out the unlabeled files with a label like "unlabeled." We will also have to deal with overlapping labels.

**Comment by rhine3** [comment]
The file naming could be a problem here--dealing with renaming files in normalized ways, directory structures and possibly generating overlaps, etc.

https://github.com/kitzeslab/opensoundscape/blob/master/opensoundscape/datasets.py#L379

**Comment by sammlapp** [comment]
was this issue fully resolved by the last release @rhine3 ?

**Comment by sammlapp** [comment]
bumping this - might be done? @rhine3

**Comment by sammlapp** [comment]
bumping again - not sure if this issue is resolved or not @rhine3

**Comment by rhine3** [comment]
Yeah, most of this was sufficiently addressed and the parts that aren't addressed are outdated.
