### ISSUE TITLE
Output .csv files

### ISSUE THREAD

**Issue by rhine3** [kitzeslab/opensoundscape#19]
Currently OpenSoundscape outputs results to the terminal. Some results make sense to output this way, e.g. AUC scores, and they can easily be redirected to a .txt file for later inspection. But other results would be easier to use if a .csv file were generated instead:

* Test results: false negative/false positive results could be a .csv. Right now, these are output with a line for each incorrectly classified test file. We might consider including a line for every test file, including the correctly classified files.
* Prediction results: these are especially important to have in .csv format--it would be a pain to deal with them otherwise. Currently the target file's name is not printed next to the prediction, which makes it a bit harder to interpret the output. Example .csv format, where `class1` column is the probability that `class1` is present in the file:

```
Filename,class1,class2
audio_files/20180101,0.9,0.2
audio_files/20180102,0.3,0.5
```

Filenames for these .csvs could be specified in the `.ini`.

**Comment by barrymoo** [comment]
Branch: https://github.com/jkitzes/opensoundscape/tree/predict_to_csv

How do you feel about simply printing it to terminal?

**Comment by barrymoo** [comment]
Prediction part completed by #34
