### ISSUE TITLE
trained model should should know length of input files

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#193]
when we save model metadata, we should store the expected input audio length. This probably means it should also be stored in the Dataset. The saved model metadata should have enough information to create a testing Dataset.

**Comment by rhine3** [comment]
I added the "discuss" label because I'm wondering what other metadata we might want to save. For instance, perhaps we want to save all the filenames of the testing/training data.

Ironically, this could be a point in favor of putting the Dataset creation inside of `train()` again...

**Comment by rhine3** [comment]
See #159 for additional suggestions

**Comment by sammlapp** [comment]
This is almost done, but the audio_length argument of preprocessor classes should be required, then stored as an attribute.
