### ISSUE TITLE
Re-evaluate default column names in some code

### ISSUE THREAD

**Issue by rhine3** [kitzeslab/opensoundscape#198]
Default column names are given for dataframes in some functions, e.g. SingleTargetAudioDataset:
https://github.com/kitzeslab/opensoundscape/blob/develop/opensoundscape/datasets.py#L232

and others:
https://github.com/kitzeslab/opensoundscape/blob/develop/opensoundscape/data_selection.py#L30
https://github.com/kitzeslab/opensoundscape/blob/develop/opensoundscape/data_selection.py#L69

This can lead to confusing failures. Potentially find and remove all of these defaults?

**Comment by chiroptical** [comment]
Please make sure to copy the static links because the first one no longer points to the right place. Either way, I agree we need to just pick a default or make these required.
