### ISSUE TITLE
Can't poetry install on cluster

### ISSUE THREAD

**Issue by rhine3** [kitzeslab/opensoundscape#207]
After following instructions for installing OPSO for development on the cluster (including linking poetry + virtualenvwrapper), found that I could `poetry install` but the created poetry environment was not found when attempting to `workon` it. 

I was able to get into the environment by `cd`ing into the root `opensoundscape` directory and running `poetry shell` but I was unable to successfully use that same procedure in a job submission script to activate the environment.

Current workaround: `poetry build` and create a new virtual environment, pip-installing from the built wheel.

**Comment by chiroptical** [comment]
I am not sure this is appropriate here? This is specific to the cluster at Pitt (likely not loading the right modules)

**Comment by sammlapp** [comment]
@rhine3 can we close this?
