### ISSUE TITLE
Create a `resume_train` function

### ISSUE THREAD

**Issue by rhine3** [kitzeslab/opensoundscape#209]
Would be nice to have a `resume_train` function if possible with features like the following:
* load up prior weights
* load state dictionary for optimizer
* recreate train and val datasets
* start saving models with correct epoch number (to be overridden if desired)

See #193 for discussion about what metadata should be saved by `train.py` to make this possible

**Comment by sammlapp** [comment]
While it won't have a separate function, resuming training will be possible simply by model.load(path) then model.train()
