### ISSUE TITLE
windows installation is difficult

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#210]
See Tiger's slack message for how he eventually succeeded. We should eventually make it easier or at least provide instructions that will consistently work for Windows users.

**Comment by chiroptical** [comment]
I think Tessa is writing this up somewhere, but I'll put it here for now. My recommended installation procedure:

##### OpSo on Windows with WSL
If not already using WSL (or don't know what it is):
- Open Powershell as administrator
- Copy and paste first command from https://docs.microsoft.com/en-us/windows/wsl/install-win10
-Restart computer

If already using WSL:
- Open Windows Store, search for "Ubuntu"
- Click "Ubuntu 20.04 LTS"
- Click "Get"
- Click "Install"
- Click "Launch"
- Set username and password to something you will remember
- `sudo apt update`
- `sudo apt install python3-pip`
- `pip3 install opensoundscape==<version>`
- `echo 'PATH=~/.local/bin:$PATH' >> ~/.bashrc`
- Close window
- Open "Ubuntu" App
- jupyter lab
- Copy and paste Jupyter link into browser
Done.

**Comment by JFK2020** [comment]
Hi. I'm just starting to learn opensoundscape on a windows machine and have encountered installation difficulties. I'm a beginner using python and have found it easier to work in Anaconda. My question is: In the above instructions, can I and at what step would I install Anaconda and are there any procedures that I should know for doing this correctly. Thanks! John

**Comment by rhine3** [comment]
Hey John, glad you found this issue! Hopefully we can get this worked out. It's really helpful, by the way, that you're testing out these instructions for us so that future Windows users don't have to struggle as much -- sorry for the difficulty in the interim.

Having not worked with WSL before I'm not 100% sure how to use it, but I believe if you want to use Anaconda, the best way to do it would be as follows:

Follow the instructions from top to bottom up to `sudo apt update`. After running `sudo apt update` do the following:

- Install Anaconda
- Get the most recent Anaconda link under the "Linux" section on this page: https://www.anaconda.com/products/individual -- currently it's `https://repo.anaconda.com/archive/Anaconda3-2020.07-Linux-x86_64.sh`
- Download Anaconda in WSL using wget, e.g. `wget https://repo.anaconda.com/archive/Anaconda3-2020.07-Linux-x86_64.sh`
- Execute the downloaded file, e.g. `wget Anaconda3-2020.07-Linux-x86_64.sh`
- Remove the downloaded file after installation, e.g. `rm Anaconda3-2020.07-Linux-x86_64.sh`
- Initialize your conda installation: run `source ~/anaconda3/bin/activate` and then after that command has run, `conda init`.
- Close and open terminal window to have access to the initialized conda
- Create a Python 3.7 conda environment for opensoundscape `conda create --name opensoundscape python=3.7`
- Activate the environment `conda activate opensoundscape`
- Install pip: `conda install pip`
- Install opensoundscape using pip: `pip install opensoundscape==<version>`
- If you want to use OpenSoundscape in JupyterLab, then open it from inside the conda environment: `jupyter lab`
- Copy and paste the jupyter lab link into your browser

Maybe @chiroptical can correct me if I'm wrong here or if I'm missing steps.

**Comment by rhine3** [comment]
Created a branch for addressing this and other recent docs improvements - https://github.com/kitzeslab/opensoundscape/tree/feat_update_docs

**Comment by chiroptical** [comment]
I made one change to your instructions.

> Execute the downloaded file, e.g. wget Anaconda3-2020.07-Linux-x86_64.sh

Should be `bash`, not `wget`.

This looks approximately correct to me. When installing `pip` into the virtual environment you might need `conda install -n opensoundscape pip`?

**Comment by rhine3** [comment]
Thanks, good catch re: `bash`. 

I think you can accomplish the pip install several ways--
- create environment, activate it, then `conda install pip` from within the environment
- one line install with `conda create -n opensoundscape pip`. 
- create environment, do not activate it, then `conda install -n opensoundscape pip`

**Comment by lydiakatsis** [comment]
Hi - I'm also having issues installing opensoundscape with Windows - I have tried both sets of instructions above, but neither seemed to work for me.

**Comment by JFK2020** [comment]
Hi lydiakatsis. I'm glad you got it to work. By Tessa's initial instructions do you mean the ones on the opensoundscape main page or the one above on this issues page?

**Comment by lydiakatsis** [comment]
Hi JFK2020 - Sorry, I mean the methods she wrote above on this issues page. The instructions on the main page didn't work for me.

**Comment by rhine3** [comment]
@lydiakatsis Thank you for updating us. It sounds like major modification you made to the instructions I wrote above was that instead of using:

```
# METHOD A
conda create --name opensoundscape python=3.7
conda activate
conda install pip
```
you used
```
# METHOD B
conda create -n opensoundscape pip
``` 
right? Did you happen to try Method A before getting Method B to work? I thought they were interchangeable, but if not, it would be good to know!

**Comment by rhine3** [comment]
I also got an email from someone else that the Anaconda install didn't work on their system, but that Barry's instructions did work:
>Ironically, I've not been able to get anaconda to install using the WSL/ubuntu option, it seems some people have been having issues with it online, so just a thought for future advice for people. I've managed to run it without anaconda and pasted a weblink into Jupyter like Barry mentioned in the issue thread.

It would be good for us to see if we can make any recommendations about when to use one procedure over another, or figure out if there's any errors or unclear points in the instructions.

**Comment by JFK2020** [comment]
Hi All, I was able to install opensoundscape using the method suggested by lydiakatsis. Thank you. Anaconda did not work for me either. I now need to know what is the command to return to opensoundscape and its path. In addition, when I type jupyter lab command in ubuntu it gives me a link to Anaconda but not opensoundscape.

**Comment by lydiakatsis** [comment]
Hi @rhine3 - yes this is correct. I tried Method A first  before moving on to this version. Unfortunately as I am a beginner with Python, I can't really tell you what the exact issue with Method A was...

**Comment by mpandit3** [comment]
I was able to get opensoundscape to work on a Windows 10 computer. I downloaded the zip file from github and manually moved the opensoundscape folder with all the .py files into the C:/Users/myusername/Anaconda3/lib/site-packages directory. I also had to download the librosa separately using pip.

**Comment by rhine3** [comment]
Hi @lydiakatsis and @JFK2020 - do you remember whether you installed WSL 1 or WSL 2?

WSL 1 would've been installed by only running the command in Step 1 from this page linked in the instructions: https://docs.microsoft.com/en-us/windows/wsl/install-win10

WSL 2 would've been installed either by following all of the rest of the steps on that page, or signing up for the Windows Insiders program and using the "easy" installation (`wsl --install`) listed as the first command on that page.

**Comment by JFK2020** [comment]
Hi rhine3. I don't remember clearly but I think I installed WSL 1.

**Comment by rhine3** [comment]
Ok, thanks @JFK2020 !

**Comment by rhine3** [comment]
After working through this on two Windows 10 computers today, I came up with the following set of Windows instructions.

# Installation instructions for Windows

### Get Ubuntu through Windows Subsystem for Linux
- Search for Powershell, right click, then click “Run as administrator” and allow it to run as administrator
- Install WSL1: `dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart` (more information: https://docs.microsoft.com/en-us/windows/wsl/install-win10)
- Restart your computer
- Open Windows Store, search for “Ubuntu” and click “Ubuntu 20.04 LTS”
- Click “Get”, wait for the program to download, then click “Launch”
- An Ubuntu shell will open. Wait for Ubuntu to install.
- Set username and password to something you will remember
- Run `sudo apt update` and type in the password you just set

### Download Anaconda
- Go to the “Linux” section on this page. Right click on the link under Linux “64-Bit (x86) Installer” and click “Copy link”`
- Download the installer: open the Ubuntu terminal and type in wget then paste the link you copied, e.g. `wget https://repo.anaconda.com/archive/Anaconda3-2020.07-Linux-x86_64.sh`.
- Execute the downloaded installer, e.g. `bash Anaconda3-2020.07-Linux-x86_64.sh` (the filename of your file may differ)
    - Press ENTER, read the installation requirements, press Q, then type “yes” and press enter to install
    - Wait for it to install
    - If your download hangs, press CTRL+C, `rm -rf ~/anaconda3` and try again
- Type “yes” to conda init
    - If you skipped this step, initialize your conda installation: run `source ~/anaconda3/bin/activate` and then after that command has run, `conda init`.
- Remove the downloaded file after installation, e.g. `rm Anaconda3-2020.07-Linux-x86_64.sh`

### Use `conda` to install OpenSoundscape
- Close and open terminal window to have access to the initialized conda
- Create a Python 3.7 conda environment for opensoundscape `conda create --name opensoundscape pip python=3.7`
- Activate the environment `conda activate opensoundscape`
- Install opensoundscape using pip: `pip install opensoundscape==0.4.6`

If you run into this error and you are on a Windows 10 machine:
```
(opensoundscape_0.4.6) username@computername:~$ pip install opensoundscape==0.4.6
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f7603c5da90>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/opensoundscape/
```
You may be able to solve it by going to System Settings, searching for “Proxy Settings,” and beneath “Automatic proxy setup,” turning “Automatically detect settings” OFF. Restart your terminal for changes to take effect. Then activate the environment and install OpenSoundscape using pip.

### Jupyterlab setup
If you want to use OpenSoundscape in JupyterLab or a Jupyter Notebook:
- Activate the conda environment
- Start JupyterLab from inside the conda environment: `jupyter lab`
- Copy and paste the JupyterLab link into your browser

**Comment by sammlapp** [comment]
these instructions are incorporated in our docs
