### ISSUE TITLE
Add Lasseck-style split and switch

### ISSUE THREAD

**Issue by rhine3** [kitzeslab/opensoundscape#220]
Add to `Spectrogram` an augmentation method to split a spectrogram at a random time, then switch the two halves. Make this a callable augmentation in  `SingleTargetAudioDataset`.

**Comment by chiroptical** [comment]
I didn't realize you had submitted. Closing #222 in favor of this.

**Comment by chiroptical** [comment]
See #241

**Comment by chiroptical** [comment]
#241 is merged.
