### ISSUE TITLE
Dataset classes should specify sampling rate

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#224]
for intance, SingleTargetAudioDataset should specify sample_rate=32000 (22050?) or take sampling rate as a parameter so that all spectrograms it produces have the same freq range

**Comment by chiroptical** [comment]
Please wait on this. These parameters need to be handled via the config file and we need to be very careful about how we propagate parameters.

**Comment by sammlapp** [comment]
the code is not useable as is, because it retains the original sampling rate of audio (if you have different sampling rates some images will get vertically squashed)

**Comment by chiroptical** [comment]
I agree. Feel free to adjust it for your use case. I am just pointing out that it might not make sense to commit it because we are going to have to change it soon.
