### ISSUE TITLE
Create separate dataset classes

### ISSUE THREAD

**Issue by rhine3** [kitzeslab/opensoundscape#233]
`SingleTargetAudioDataset` is starting to get unwieldy in its length. 

Plus, it now contains functionality that can cause serious bugs if not used thoughtfully: see https://github.com/kitzeslab/opensoundscape/pull/231. After this PR, if you are creating a binary model, `overlay_class` *always* ought to be set equal to the absent class label. But one could theoretically use `overlay_class = 'different'`, representing overlays from any class, for a multi-class model. Ideally, instead of making this bug possible, we would just create two separate datasets, one for multi-class models and one for binary models.

It would be good to move to subclassing for datasets. We could have a base `AudioDataset` class with standard functionality that doesn't vary much between datasets. Then we subclass from it, e.g. `BinaryClassifierAudioDataset`, `MultiClassSingleTargetAudioDataset`, `MultiClassMultiTargetAudioDataset`.

The base class might also contain some functionality that serves as a template for subclasses, even if the functionality is too basic to realistically use in a model (e.g. a simpler `__getitem__`)--just something that I've noticed in Miao's code.

**Comment by rhine3** [comment]
This should be a long-term goal for our next big version increment (OPSO 0.5)

It might be better to write a system where people can write augmentation pipelines and provide some default pipelines instead of creating multiple classes.

This should tie in with our progress on using ini/config files

**Comment by sammlapp** [comment]
flexible datasets in #270 using the preprocessors module
