### ISSUE TITLE
Implement GradCAM on prediction spectrograms

### ISSUE THREAD

**Issue by rhine3** [kitzeslab/opensoundscape#237]
Need to incorporate Miao's code into the API + add a notebook

**Comment by sammlapp** [comment]
Lydia mentioned this to me today - she's hoping to use GradCam if we can get it working soon

**Comment by louisfh** [comment]
We could use the pytorch-grad-cam package https://github.com/jacobgil/pytorch-grad-cam for various saliency methods including gradCAM. Note: some of these methods can increase inference time a lot (~10-fold or more)

If we want to integrate gradcam into OpSO Api we could:

call a saliency/interpret method of the object e.g.
`model.saliency(dataset, method="gradCAM")`

pass it as an argument to a model.predict call. 

Have a standalone gradcam module/function.

An implementation note is that for each model architecture we will need to specify a target layer at which Class Activation Maps are computed. This could be done for our existing architectures, but could be an issue if a user tries to use their own architecture.

**Comment by louisfh** [comment]
We will make a tutorial notebook showing how to use pytorch-grad-cam to make heatmap images overlaid on spectrograms, and how to use them to interpret a model (as well as the pitfalls of using these methods). Then we can choose to later integrate gradCAM and/or other saliency methods into opensoundscape.

**Comment by sammlapp** [comment]
Does such a tutorial notebook exist now @louisfh? I can' remember. It would be a great addition to [the cookbook](https://github.com/kitzeslab/bioacoustics-cookbook)

**Comment by louisfh** [comment]
We've now decided to actually implement this within a module of its own in Opso. Or perhaps as a method of a model object.
