### ISSUE TITLE
Add grayscale option to Spectrogram.plot()

### ISSUE THREAD

**Issue by rhine3** [kitzeslab/opensoundscape#238]
We should have the option to use a grayscale spectrogram here, or make grayscale the default. Grayscale is what is actually seen by machine learning (and I strongly prefer it)

https://github.com/kitzeslab/opensoundscape/blob/07d7965f4529db6b2fec0a3f988f591d8ca8b921/opensoundscape/spectrogram.py#L250-L277

**Comment by sammlapp** [comment]
yeah there was a branch somewhere that changed this but it never got merged. it should be only greyscale

**Comment by chiroptical** [comment]
You just need to add `cmap="greys"` to `plt.pcolormesh`?
