### ISSUE TITLE
Audio.trim() should round sample numbers to integers 

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#248]

**Comment by chiroptical** [comment]
I don't understand this comment?

https://github.com/kitzeslab/opensoundscape/blob/197475e4bd91677ae4405d43e6a6010b317241a8/opensoundscape/audio.py#L142-L159

calls, `self.time_to_sample` which rounds to an integer?

https://github.com/kitzeslab/opensoundscape/blob/197475e4bd91677ae4405d43e6a6010b317241a8/opensoundscape/audio.py#L179-L187

**Comment by sammlapp** [comment]
yeah I'm actually not sure what happened but I think I misinterpreted the error message

**Comment by sammlapp** [comment]
I got a weird error when the file length was too short, so thats something we should address but I'm closing this issue

**Comment by sammlapp** [comment]
Depending on something (operating system? version of python?) the result of round() can be a float and cause a failure when you take a slice of an array (ie 10.0 vs 10). time_to_sample  should use int(time * self.sample_rate) instead.

**Comment by sammlapp** [comment]
additionally, int() rather than int(round()) because trim(t,t+b) should always return a consistent length file regardless of t. round() would not always return the same length of audio for fixed b and different t.
