### ISSUE TITLE
prediction fails on bad file

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#249]
If there is a bad file (for instance, 0Bytes) in a list of millions of files, the entire prediction (or training, presumably) fails. The data loader should probably just give some warning and continue working so that the whole thing doesn't fail.

**Comment by rhine3** [comment]
Possibly related to #236 where I observed failures during training, but couldn't track them down to 0B files

**Comment by sammlapp** [comment]
resolved by #270
