### ISSUE TITLE
splitting creates 0B files

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#250]
Splitting code should not write files that are 0bytes (or anything less than some cutoff). I'm not sure why this even happens because the splitting code default is to drop any excess audio that doesn't make a full-length clip.

**Comment by jkitzes** [comment]
Could they be "split" from an original file thats 0 b or otherwise corrupt?

**Comment by sammlapp** [comment]
yes could be. but the proper default behavior for a 0 byte file would be to make zero clips

**Comment by sammlapp** [comment]
Justin hypothesis: caused by the bug with rounding samples. After changing round() to int() in time_to_sample, check if this still happens

**Comment by sammlapp** [comment]
this *seems* to have been resolved by the change mentioned above (round() to int() in time_to_sample)
