### ISSUE TITLE
Revise `Audio.extend()` vs. `Audio.loop()`

### ISSUE THREAD

**Issue by rhine3** [kitzeslab/opensoundscape#265]
Re: https://github.com/kitzeslab/opensoundscape/pull/262#discussion_r605624061

The name of the "extend" function is misleading, since it loops audio. Possibly rename it to `Audio.loop()` or `Audio.repeat()` then add a true `Audio.extend()` feature which extends a file with silence.

This will require changes throughout the code wherever the "extend" behavior is referenced, e.g. in `raven.py`

**Comment by sammlapp** [comment]
@rhine3 I think if the desired behavior is just extending, we can just change the Audio class and leave everything else as is. Are there places we want to use loop()?

**Comment by sammlapp** [comment]
#270 changes extend() to loop(), and adds an extend() to extend audio with silence. loop will have 2 modes, looping to a fixed duration or looping n times.

**Comment by rhine3** [comment]
Integrated into Raven features as well by 07b461170de577ea027a82658f362ea5e0d15a76

**Comment by sammlapp** [comment]
not done until #270 is merged. also loop requires kwd argument

**Comment by sammlapp** [comment]
resolved in #270
