### ISSUE TITLE
Soundscape Indices? 

### ISSUE THREAD

**Issue by abfleishman** [kitzeslab/opensoundscape#271]
Cool tools you are developing! 

I am interested if you have plans to add python based soundscape analysis tools to this work?

**Comment by sammlapp** [comment]
Hi @abfleishman, 
Yes, we plan to add some acoustic index/soundscape analysis tools. We will most likely use https://github.com/patriceguyot/Acoustic_Indices as a starting place. We are curious what features or specific tools you would find most useful, especially if they are not included in the Acoustic_Indices implementation. It would also be interesting to hear about any specific use cases you have for soundscape analysis.

**Comment by abfleishman** [comment]
@sammlapp My question yesterday was prompted by a conversation with @aykuznetsova about creating an open-source python-based, scaleable, dockerized, soundscape index calculation package as part of an internal project with @ConservationMetrics.  We were also talking about starting with the [Acoustic_Indices](https://github.com/patriceguyot/Acoustic_Indices) library.  

But I know your lab has been working a lot on the `opensoundscape` repo and I was interested to see if the indices were in your plan at some point.  Seems like a good place for us to collaborate. 

We have used Acoustic Indices in projects comparing avian point count diversity indices to acoustics.  But we are interested in quantifying change after management/conservation actions.  In the past, we have used the QUT [Analysis Programs](https://github.com/QutEcoacoustics/audio-analysis)  but the 1 minute sound files we are normally working with make the resulting output from their software miserable to work with.  I do not remember the indices we had the best results with, but it is on my to-do list to create a list of indices and the primary source (paper, package) that those indices come from that we are interested to have access to internally.  

Honestly, there are so many indices that have been tried and written about in the literature, but they are all spread across many softwares and languages (r, python, C#) what I really dream of is a place to coalesce all the math into a single package, and a help file/documentation that would walk a potential user through index selection and use cases (from the literature?).

**Comment by sammlapp** [comment]
Great - it sounds like we should definitely hop on a call sometime, I'll try to get Justin and Tessa on it as well. You can ping me at sam.lapp@pitt.edu.

**Comment by sammlapp** [comment]
@abfleishman as you may have noticed, this project fell by the wayside for us. If you are interested in contributing to opensoundscape by adding a module that implements acoustic indices, you are welcome to fork the repo.

**Comment by abfleishman** [comment]
Yes, I did notice. We have headed in a different direction and are using [scikit-maad](https://scikit-maad.github.io/) to calculate indices.  Thanks for the update
