### ISSUE TITLE
logging and verbose switches for training and prediction

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#281]
cnn.PytorchModel doesn't have logging or custom verbose switches implemented for .train() and .predict(), these would be useful.

**Comment by sammlapp** [comment]
Jatin also mentioned adding progress bars and/or other useful output

**Comment by sammlapp** [comment]
also remove any extra print statements

**Comment by jatinkhilnani** [comment]
> also remove any extra print statements

Found the culprit printing shape of total scores output in `predict` method, commented out.

**Comment by sammlapp** [comment]
added model attributes `logging_level` and `verbose` as well as `log_file`, which control logging and printed output verbosity.
