### ISSUE TITLE
Add audio metadata extraction tool 

### ISSUE THREAD

**Issue by rhine3** [kitzeslab/opensoundscape#287]
Add a tool that allows you to extract metadata from AudioMoth WAV headers, especially:
* temperature logging data
* timezone information

**Comment by sammlapp** [comment]
the package tinytag does this nicely for audio files in general

The AudioMoth metadata format is like this


```
 {"album": null, "albumartist": null, "artist": "AudioMoth 24F319025D320451", "audio_offest": 480, "audio_offset": null, "bitrate": 500.0, "channels": 1, "comment": "Recorded at 01:30:00 15/05/2021 (UTC) by AudioMoth 24F319025D320451 at medium gain setting while battery state was 4.6V and temperature was 17.7C.", "composer": null, "disc": null, "disc_total": null, "duration": 5400.0, "extra": {}, "filesize": 345600488, "genre": null, "samplerate": 32000, "title": null, "track": null, "track_total": null, "year": null}
```

So to get the temperature we need to parse the value of the "comment" field. Grabbing the UTC timestamp and AudioMoth ID, and gain setting from the "comment" field would also be awesome.

**Comment by sammlapp** [comment]
consider saving metadata dictionary into Audio.metadata when using Audio.from_file()

**Comment by sammlapp** [comment]
done in `issue_287_moth_tools` branch
