### ISSUE TITLE
Tutorial notebooks require ffmpeg

### ISSUE THREAD

**Issue by louisfh** [kitzeslab/opensoundscape#298]
The RIBBIT and raven tutorial notebooks both use mp3 files. These require ffmpeg to be installed, otherwise a NoBackendError will be thrown when trying to load the audio. This is slightly cryptic for new users. A note about this could be added to these notebooks.

**Comment by sammlapp** [comment]
resolved the issue in annotations tutorial - the ribbit tutorial isn't fixed yet, because it accesses online files
