### ISSUE TITLE
use curl instead of wget in tutorial

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#299]
The raven tutorial uses wget to download data, but I don't think wget is something most people will have - specifically, Evelyn had trouble with it and got stuck on this step.

**Comment by jkitzes** [comment]
@sammlapp I can make this change. Do we know if `curl` installed on Windows subsystem by default?

**Comment by louisfh** [comment]
This can be handled by the python standard libary `requests` package. This does not require much code but for clarity/concision in tutorial notebooks should probably be implemented by a helper function.
