### ISSUE TITLE
Multi-channel audio

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#305]
Add support for multi-channel audio, such as stereo audio. Then add feature for mixdown to mono. I guess the current behavior is that everything gets mixed down to mono automatically, but not sure

**Comment by sammlapp** [comment]
for now, we could just enable the user to load a specific channel of an audio file into an Audio

**Comment by sammlapp** [comment]
ie, Audio.from_file(path, channel=0)

**Comment by sammlapp** [comment]
instead, I implemented a function `load_channels_as_audio` to load multi-channel audio as separate audio objects, one per channel

**Comment by sammlapp** [comment]
I'm re-opening this issue because we should consider adding full support for multi-channel audio, rather than just a way to load multi-channel audio into mono Audio objects

**Comment by Maxime-Bru** [comment]
I have a model trained on mono wav files and I want to apply it to the left channel of stereo wav files. Currently, when doing model.predict(), my stereo files are mixed to mono (librosa standard load behavior). Is there a way to apply my model only on the left channel of my wav files? I know I could manually remove the right channel for all my wav files and then use the model but this is not very convenient.
Thanks for your help!

**Comment by sammlapp** [comment]
Hi @Maxime-Bru , I'd recommend making an alternative version of the AudioClipLoader class, which is the class used in the `model.preprocessor.pipeline.load_audio` preprocessing Action
https://github.com/kitzeslab/opensoundscape/blob/1b3e1211e1b01c06120688dd87d15eb699ac7fc3/opensoundscape/preprocess/actions.py#L280

Note that by using the decorator @register_action_cls, you could save this modified model object and re-load it and it will retain your custom preprocessing operation (you'll still need the code defining the custom class is in your script/imported from a utils module)

Here's a working example:
```python
import opensoundscape as opso

m = opso.CNN("resnet18", classes=[0], sample_duration=2)


@opso.preprocess.action_functions.register_action_fn
def load_one_channel(
    file, sample_rate=None, offset=0, duration=None, channel=0, **kwargs
):
    a = opso.audio.MultiChannelAudio.from_file(
        path=file, sample_rate=sample_rate, offset=offset, duration=duration, **kwargs
    )
    # just return the audio signal from one channel as an Audio object
    # will raise IndexError if channel >= number of channels
    # use 0 for first channel!
    return a.to_channels()[channel]


@opso.preprocess.actions.register_action_cls
class AudioClipLoaderFirstChannel(opso.preprocess.actions.Action):
    """Action to load clips from an audio file, only selecting the first channel

    Loads an audio file or part of a file to an Audio object.
    Will load entire audio file if _start_time and _end_time are None.
    If _start_time and _end_time are provided, loads the audio only in the
    specified interval.

    Args:
        see Audio.from_file()
    """

    def __init__(self, **kwargs):
        if "fn" in kwargs:
            kwargs.pop("fn")
        super().__init__(fn=load_one_channel, **kwargs)
        # two params are provided by sample.start_time and sample.duration
        self.params = self.params.drop(["offset", "duration"])

    def __call__(self, sample, **kwargs):
        # this function should update sample.data in place,
        # turning it from a path into an Audio object

        # at this point in preprocessing, sample.data is a file path
        # sample also has .start_time and .duration
        offset = 0 if sample.start_time is None else sample.start_time
        duration = None if sample.duration is None else sample.duration
        # replace sample.data with the Audio object loaded using first channel
        sample.data = self.action_fn(
            sample.data, offset=offset, duration=duration, **dict(self.params, **kwargs)
        )
m.preprocessor.pipeline.load_audio = AudioClipLoaderFirstChannel(
    channel=0, sample_rate=None, out_of_bounds_mode="ignore"
)
# check that it works by loading a single 2s audio clip

f = "/Users/SML161/sample_audio/soundscape_stereo.mp3"
start_t = 5
s = m.preprocessor.forward((f, start_t), break_on_key="to_spec")
s.data

# use the model
m.predict("/Users/SML161/sample_audio/soundscape_stereo.mp3")

# can save it too:
#m.save("my_model.model")
#m2 = opso.
# opso.ml.cnn.load_model("my_model.model")
# use the model
m.predict("/Users/SML161/sample_audio/soundscape_stereo.mp3")
```

**Comment by Maxime-Bru** [comment]
Thank you so much!

In the future, do you plan to add a fourth index "channel" to your multi-index format (file, start_time, end_time) ? To me, it would seem appropriate and useful but maybe there are technical issues I'm not aware of.

**Comment by sammlapp** [comment]
We don't currently have plans to do this. I will keep the idea in mind for the future though.
