### ISSUE TITLE
Display action default params 

### ISSUE THREAD

**Issue by rhine3** [kitzeslab/opensoundscape#326]
We can't see the parameter defaults for things like `AudioToSpectrogram` because these defaults are contained by the function that is called in `go()`. Defaults are manually listed in the docstring but if the defaults of the called function are changed, the docstring could silently fall out of date.

Perhaps all default parameters should be explicitly written in the Action? This would also make it easier to keep a record of what parameters were used in a particular machine learning pipeline--just print and save the `.params` attribute of every step in the pipeline. (Though, related to #325, can't tell whether an Action is on or off based on the pipeline alone)

**Comment by sammlapp** [comment]
I couldn’t think of a good way todo this. The defaults should not be hard coded, because then changing the defaults in the original code would create an inconsistency if the Action is not updated.

**Comment by sammlapp** [comment]
This was resolved by having a generic Action class that loads all required and optional arguments from the function it will run with go(). It will not allow the user to "change" non-existant parameters with the .set() method of setting parameter values.
