### ISSUE TITLE
Standardize "ResNet" capitalization

### ISSUE THREAD

**Issue by rhine3** [kitzeslab/opensoundscape#329]
Both `ResNet` and `Resnet` are used as capitalization in OPSO classes (e.g. `ResNetArchitecture` vs. `Resnet18Binary`). We should standardize. The standard/expected capitalization is `ResNet`, but it would be a smaller change to switch everything to `Resnet`.

**Comment by louisfh** [comment]
The timm package for example uses 'ResNet' for its resnet classes https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/resnet.py
