### ISSUE TITLE
Add learning rate scheduling parameters to `optimizer_params` dict?

### ISSUE THREAD

**Issue by rhine3** [kitzeslab/opensoundscape#330]
In `Resnet18Binary` and potentially other classes, the `model.optimizer_params` dictionary does not include `lr_cooling_factor` and `lr_update_interval`. 

https://github.com/kitzeslab/opensoundscape/blob/58eee0dfe473ee73f53bd615773c88f493e2c52e/opensoundscape/torch/models/cnn.py#L100-L101

If it wouldn't break anything, could we store them all in the same place? Would help with ease of seeing parameters by calling `model.optimizer_params` and would preserve parallelism when updating these parameters using calls like `model.optimizer_params['feature']['lr']=0.01`

(If it would break something, I want to remove the call to `model.optimizer_params` from the `cnn_training_advanced.ipynb` notebook because it's confusing otherwise)

**Comment by sammlapp** [comment]
Unfortunately I think I had it like this but it broke things. Can check though. The initialization of the optimizer object expects a dictionary of a specific structure, and .optimizer_params is that dictionary.

**Comment by rhine3** [comment]
Ah, that's too bad, but good to know. Feel free to close this if it can't be done.

**Comment by sammlapp** [comment]
Closing for now. Note that above, Tessa said
"(If it would break something, I want to remove the call to model.optimizer_params from the cnn_training_advanced.ipynb notebook because it's confusing otherwise)" 
so that change may still be necessary
