### ISSUE TITLE
model.train not saving at correct interval

### ISSUE THREAD

**Issue by rhine3** [kitzeslab/opensoundscape#341]
When using `save_interval=1` during training it appears my model has gone through at least 10 epochs and only saved the 10th. The save directory contains only two models:
```
$ ls train_aug/
best.model  epoch-9.model
```

The code that this happened with:

```
sp='eato'
train_df = pd.read_csv(f"labels/{sp}_train.csv", index_col='filename')
valid_df = pd.read_csv(f"labels/{sp}_valid.csv", index_col='filename')
classes = train_df.columns
print("Current time:", time.time())

# Train a model with typical augmentation level
print("\n\nTraining model with typical augmentation for", sp)
train_dataset_aug = CnnPreprocessor(train_df)
valid_dataset_aug = CnnPreprocessor(valid_df)
model_aug = Resnet18Binary(classes)
model_aug.train(
    train_dataset=train_dataset_aug,
    valid_dataset=valid_dataset_aug,
    save_path=f'./train_aug_{sp}/',
    epochs=3,
    batch_size=64,
    save_interval=1,
    num_workers=0,
)
```

It's not immediately obvious why this happened from this section of code:
https://github.com/kitzeslab/opensoundscape/blob/3a038e68297743d61338bc946e5577fc4d78d420/opensoundscape/torch/models/cnn.py#L380-L393

**Comment by rhine3** [comment]
Nevermind. You don't even want to know where I went wrong on this one.

**Comment by sammlapp** [comment]
Yay! We've all been there 🥳
