### ISSUE TITLE
valid_metrics and train_metrics are the same

### ISSUE THREAD

**Issue by lydiakatsis** [kitzeslab/opensoundscape#342]
Not sure if this is a mistake that I've made, but when I call model.valid_metrics.values()  and model.train_metrics.values(), the values for precision, recall etc are all exactly the same for training and validation.

**Comment by rhine3** [comment]
Additional question from Phil related to metrics:

> I am running in to a confusing issue. I run a model for say, 20 epochs, saving and so on. The precision/recall stays consistent -- say around 0.8 and 0.7. I then restart the model from either the 'best model' or the last epoch saved, and it immediately start reporting a completely unrealistic precision recall that is essentially 1 (0.998 or whatever). Is this user error of some type? 
>
> A related issue is that I can't find anywhere exactly what parts of the model output (model.*) I should look at ... for example, if I have a set of saved epochs, what would a script look liked that went through those and recovered the same information that usually gets displayed to the screen (well, I suppose I could just look at your code, but I guess the question is more general).

**Comment by sammlapp** [comment]
in cnn.py save() need to fix bug  at line 452:


```
            "valid_metrics": self.valid_metrics,
            "train_metrics": self.valid_metrics,
```

I will do this very soon

**Comment by lydiakatsis** [comment]
This is still not solved for me - it is solved if I look at model models straight after training model, but not when I load the saved best model (goes back to original issue)

**Comment by lydiakatsis** [comment]
I'm still having an issue here - issue is resolved when inspecting metrics straight after training model, but when loading model the original issue returns

**Comment by sammlapp** [comment]
I'm not sure why you still have the issue. @lydiakatsis are you using the latest version of the develop branch? (The fix has not been pushed to the master branch, only develop).
