### ISSUE TITLE
Continuing training of CNN from loaded model may not be working

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#351]

**Comment by jkitzes** [comment]
Is there any chance this is somehow related to #344 ?

**Comment by sammlapp** [comment]
Yep, definitely possible, but I probably won't know until I find the bug

**Comment by sammlapp** [comment]
Found the bug. It's caused by overwriting the optimizer_params attribute with the one from the old model
`self.optimizer_params = model_dict["optimizer_params"]`

Since optimizer_params contains a list of the model.network's "parameters" meaning the actual weights, that list is somehow out of date in that it corresponds to the old object, not the current one. 

A patch that works, though its not elegant: re-establish the current model's parameter list in the optimizer params after over-writing
```
    model.optimizer_params = model_dict["optimizer_params"]
    model.optimizer_params["params"]=model.network.parameters()
```

or, for the models with feature and classifier blocks (Resnet18Binary and Resnet18Multiclass):
```
    model.optimizer_params = model_dict["optimizer_params"]
    model.optimizer_params["feature"]["params"]=model.network.feature.parameters()
    model.optimizer_params["classifier"]["params"]=model.network.classifier.parameters()
```

A better solution would be to have optimizer_params just store the actual training parameters. Then in _init_optimizer(), add in the key "params"=model.network.parameters(). 

I'll fix this soon and try to get into develop asap

**Comment by sammlapp** [comment]
The bug found above still seems like it caused the problem, but it only occurs when a new python kernel is used. If the same python process trains a model, saves it, then reloads it and continues training, I don't see the issue. This tripped me up when I was trying to reproduce the issue in a notebook, and is probably why we didn't notice the issue when the feature was initially implemented.
