### ISSUE TITLE
Preprocessors should avoid using PIL.Image

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#352]
To allow flexibility in the number of channels (other than 1, 3 for greyscale vs RGB) we should go directly from Spectrograms to Tensors. Augmentations that currently happen on images can easily be modified to act on Tensors.

**Comment by louisfh** [comment]
This issue was raised because it could simplify our dependencies, and in the past PIL as a dependency has caused problems.

**Comment by sammlapp** [comment]
I updated the preprocessing module to not use PIL image. However, I haven't completely removed PIL as a dependency, because it is used elsewhere (eg spectrogram.to_image). We could decide to remove it everywhere if we want, if so we should open a new issue.
