### ISSUE TITLE
Consider using ~ instead of ^ in poetry dependencies

### ISSUE THREAD

**Issue by jkitzes** [kitzeslab/opensoundscape#355]
We currently use the ^ syntax for our poetry dependencies, which allows the newest package within a major version (or minor version if package is in 0.x.x). See https://python-poetry.org/docs/dependency-specification/.

I think that we might want to consider changing to ~, which will allow anything newer. This is more likely to fail as we get package conflicts. But it will "automatically" allow us to use newest versions of dependencies, whereas under our current setup we have to manually update the dependency when there's a version increment - it seems likely we'll fall behind on this.

**Comment by sammlapp** [comment]
sounds good
