### ISSUE TITLE
Bulleted lists not rendering in sphinx

### ISSUE THREAD

**Issue by jkitzes** [kitzeslab/opensoundscape#361]
Apparently this is an issue with `sphinx` and the newest `docutils` -

https://stackoverflow.com/questions/67542699/readthedocs-sphinx-not-rendering-bullet-list-from-rst-file

Pinned `docutils` to 0.16 for now to solve, watch this issue for resolution

https://github.com/readthedocs/sphinx_rtd_theme/issues/1115

**Comment by sammlapp** [comment]
looks like it was resolved in https://github.com/readthedocs/sphinx_rtd_theme/pull/1185#issue-962980233
so we can unpin docutils @jkitzes ?

**Comment by jkitzes** [comment]
It's possible this was also fixed by our Jupyter revisions? Yes I think we can unpin but let's hold until we unpin everything necessary at once and make sure tests pass.
