### ISSUE TITLE
(Re)consider whether validation data should have augmentation

### ISSUE THREAD

**Issue by jkitzes** [kitzeslab/opensoundscape#365]
In prediction tutorial (and in our work) we had previously decided that we should apply augmentation to our validation data, the same as to training. With augmentation, validation scores reflect how well training is generalizing to similar unseen data. Without augmentation, validation scores reflect how well model will generalize to new data (at least something like this, this is most true if train and validation are both random subsets from prediction data).

**Comment by sammlapp** [comment]
#227 was the original issue opened for this
