### ISSUE TITLE
Pip install ends with:  Could not find a version that satisfies the requirement ray<0.9.0,>=0.8.5

### ISSUE THREAD

**Issue by rduivenvoorde** [kitzeslab/opensoundscape#375]
Hi,

Running Python 3.9.7 here on a Debian Testing laptop.

After creating a virtual environment, I tried to use `pip3 install opensoundscape==0.5.0` but that ended with:

```
ERROR: Could not find a version that satisfies the requirement ray<0.9.0,>=0.8.5 (from opensoundscape)
ERROR: No matching distribution found for ray<0.9.0,>=0.8.5
```

Just using `pip3 install opensoundscape` seems to install an older version? Have to find that out first...
Ah yes:
```
>>> opensoundscape.__version__
'0.1.0'
```

Using `pip install ray` I get version 1.6.0 installed:
```
Downloading ray-1.6.0-cp39-cp39-manylinux2014_x86_64.whl (49.3 MB)
```
Trying to install opensoundscape 0.4.7 fails with a torch version error

Any hints on these? I'm eager to play with this for bat sounds...

**Comment by rduivenvoorde** [comment]
Mmm, created a virtual environment for Python 3.7.7 but got the same error...?

**Comment by rduivenvoorde** [comment]
Ok, it looks like this is a Debian issue. You should be able to create virtual environments with different python runtime versions, BUT creating a 3.7 fails (because it either does NOT install pip, OR (if you do not install it) it uses the 3.9 pip version and packages....).

The good news: using Conda I'm able to install a 3.7 environment and run opensoundscape!

I hope development will continue so newer Python version will be supported.

**Comment by sammlapp** [comment]
Glad to hear you were able to resolve this - we plan to support newer Python versions soon.
