### ISSUE TITLE
Ribbit score times out of sync

### ISSUE THREAD

**Issue by lydiakatsis** [kitzeslab/opensoundscape#378]
Time of scores doesn't line up with the times of the spectrogram - e.g. for an 8.5 second recording, window start time goes from 0 - over 10. 

This issue is related to window overlap in the spectrogram - when window overlap on the spectrogram is set to 0 the issue doesn't appear.

**Comment by sammlapp** [comment]
addressed in branch issue_378_ribbit_bug
