### ISSUE TITLE
Tutorial notebook with annotation helper tools

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#397]
Add a notebook like the ones Pat and Lydia are using - creates spectrograms, plays sounds, accepts user annotations

**Comment by jatinkhilnani** [comment]
[TDL notebook](https://github.com/kitzeslab/bioacoustics-cookbook/blob/main/top-down-listening.ipynb) has been released to [bioacoustics-cookbook](https://github.com/kitzeslab/bioacoustics-cookbook) repository.
