### ISSUE TITLE
enable timestamp-based Audio trimming / extraction

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#405]
something like `get_time_period(audio, start_time=timestamp, duration)`
- start_time: enforce that it is a localized datetime object
- only works if audio.metadata['recording_start_time'] is a localized timestamp

**Comment by sammlapp** [comment]
just for audiomoth

**Comment by louisfh** [comment]
Audiomoths have a standard format for writing time into filename. However this doesn't include timezone. So we should use the time in the metadata.

**Comment by sammlapp** [comment]
instead of enforcing only audiomoth files, we can check if the audio has a start timestamp in the metadata in a specific field.
