### ISSUE TITLE
failing to parse UTC-5 timezone in metadata

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#457]
audiomoth.parse_audiomoth_metadata() is failing to parse metadata that includes a timezone from firmware 1.5.0. (I think this might only happen when the audiomoth is programmed to use a different timezone than UTC). 

Example metadata:

```
{"album": null, "albumartist": null, "artist": "AudioMoth 24E144055DDD3203", "audio_offest": 480, "audio_offset": null, "bitrate": 500.0, "channels": 1, "comment": "Recorded at 19:22:55 14/12/2020 (UTC-5) by AudioMoth 24E144055DDD3203 at medium gain setting while battery state was 4.0V and temperature was 24.5C.", "composer": null, "disc": null, "disc_total": null, "duration": 10.0, "extra": {}, "filesize": 640488, "genre": null, "samplerate": 32000, "title": null, "track": null, "track_total": null, "year": null}
```

leads to UnknownTimeZoneError: 'UTC-5'

so we need to parse the timezone string differently.

**Comment by lmc150** [comment]
I received a warning when trying to predict on files:
```
UserWarning: This seems to be an AudioMoth file, but parse_audiomoth_metadata() raised: could not convert string to float: 'les'
  "This seems to be an AudioMoth file, "
```
The metadata of the first file in the set is:
`{"album": null, "albumartist": null, "artist": "AudioMoth 249BC3055C02FE06", "audio_offest": 480, "audio_offset": null, "bitrate": 500.0, "channels": 1, "comment": "Recorded at 10:00:00 15/05/2021 (UTC) by AudioMoth 249BC3055C02FE06 at medium gain setting while battery state was less than 2.5V and temperature was 2.1C.", "composer": null, "disc": null, "disc_total": null, "duration": 7200.0, "extra": {}, "filesize": 460800488, "genre": null, "samplerate": 32000, "title": null, "track": null, "track_total": null, "year": null}`
