### ISSUE TITLE
add EfficientNet architecture

### ISSUE THREAD

**Issue by JacobGlennAyers** [kitzeslab/opensoundscape#478]
We noticed that the new BirdNET-Analyzer framework has migrated into using EfficientNet. I was curious if there have been any experiments with OpenSoundscape and Pytorch's EfficientNet capabilities?

**Comment by sammlapp** [comment]
Hi Jacob, thanks for your question. We haven't used EfficientNet so far with opensoundscape, but you could pretty easily use Pytorch's EfficientNet in opensoundscape if you wanted to by creating the EfficientNet object with an appropriate number of output nodes and using it as the "architecture" for the CNN class. (For examples of how we do this with other algorithms, see the cnn_architectures module.) 

I'll leave this issue open. We'll probably add EfficientNet support (along with any other new architectures supported by PyTorch) in the next minor release.
