### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by carlybatist** [kitzeslab/opensoundscape#514]
I am having problems installing opensoundscape on a 16GB Macbook Air with M1 chip running macOS Monterey 12.4. I follow the instructions on the website verbatim (i.e., conda activate opensoundscape, pip install opensoundscape==0.7.0), but in the install I get thrown a bunch of errors about wheels not forming and a bunch of other stuff I don't really understand. And then if I try to call any functions from the package it says 'ModuleNotFoundError' because I guess the package wasn't actually successfully installed. The text of the error is attached.  
[opensoundscape errors.md](https://github.com/kitzeslab/opensoundscape/files/9189749/opensoundscape.errors.md)

**Comment by carlybatist** [comment]
<img width="1312" alt="Screen Shot 2022-07-26 at 11 41 22 AM" src="https://user-images.githubusercontent.com/46716228/181049968-812a163f-45c5-4843-a561-bd365b2a45e9.png">
FYI I am also getting these errors when trying to install in Colab

**Comment by louisfh** [comment]
Regarding the colab error - these are dependency conflicts that pip is warning you about. You should be able to click the 'restart runtime' button and again execute the cell that installs OpenSoundscape - it should execute again without any error messages. Even without restarting the runtime the colab will probably work fine.

I'll take a look at the issue with your local install.

**Comment by carlybatist** [comment]
I did the restart runtime and it was giving me an error still, up until right now when I re-opened my colab and it just worked with me doing the same exact thing...I have no idea why it wasn't working and hour ago but magically is now. I did the runtime restart both times.

**Comment by louisfh** [comment]
OK - btw thanks for raising the issue!

Which version of Python are you using? Creating an environment using Py3.7 or Py3.8 (which is all we officially support at present) work for me on an M1 machine with both miniforge and conda. e.g. this works fine:
```
conda create --name opensoundscape_env python=3.8
pip install opensoundscape
```

To check that the correct python and pip are being used within the environment you can execute `which python` and `which pip`. `which pip` should return something like `/path/to/env/bin/pip`.
