### ISSUE TITLE
Getting error in split() - 'call_duration not keyword argument'

### ISSUE THREAD

**Issue by carlybatist** [kitzeslab/opensoundscape#515]
I am trying to run the following code and am running into an error that says call_duration is not a keyword argument for split()

```
#splitting annotations along with audio, to train models on short segments
#load the Audio and Annotations
from opensoundscape.audio import Audio
from opensoundscape.spectrogram import Spectrogram
from opensoundscape.annotations import BoxedAnnotations
from pathlib import Path
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
from glob import glob
from opensoundscape.helpers import generate_clip_times_df
audio_file = 'audiomoth2_20211217_061100.WAV'
annotation_file = 'audiomoth2_20211217_061100.selections.txt'

#split the audio into 5 second clips with no overlap (we use _ because we don't really need to save the audio clip objects for this demo
clip_duration = 5
_, clip_df = audio_file.split(clip_duration=clip_duration, clip_overlap=0)
labels_df = annotation_file.one_hot_labels_like(clip_df,min_label_overlap=0.25)

#the returned dataframe of one-hot labels (0/1 for each class and each clip) has rows corresponding to each audio clip
labels_df.head()`
```

Screenshot of the full error message attached, and I've also attached the txt file I'm trying to test out here (my end goal is to batch process this for all my files [~200], but I get the same call_duration error when doing the code that runs this function over multiple files. Apparently .wav files are not supported by Github here so I can't attach the audio file.

<img width="590" alt="Screen Shot 2022-07-27 at 4 10 09 PM" src="https://user-images.githubusercontent.com/46716228/181392998-85d3856f-470a-4bf1-a51b-356b363ff05c.png">
[audiomoth2_20211217_061100.selections.txt](https://github.com/kitzeslab/opensoundscape/files/9204295/audiomoth2_20211217_061100.selections.txt)

**Comment by rhine3** [comment]
The bug in these scripts is that both the `audio_file` and the `annotation_file` are strings of filenames, instead of the needed OpenSoundscape classes for audio and annotation files. For example, in the first script:
```
audio_file = 'audiomoth2_20211217_061100.WAV'
_, clip_df = audio_file.split(clip_duration=clip_duration, clip_overlap=0)
```

`audio_file` is a string, so this is using the "split" function for strings, not OpenSoundscape's function. 

To solve this, load `audio_file` into an `Audio` object and `annotation_file` into a `BoxedAnnotation` object, e.g.

```
# Load the files into the needed OpenSoundscape classes
audio_file = Audio.from_file('audiomoth2_20211217_061100.WAV')
annotation_file = BoxedAnnotations.from_raven_file('audiomoth2_20211217_061100.selections.txt')

# Split the audio file
_, clip_df = audio_file.split(clip_duration=clip_duration, clip_overlap=0)

# Split the annotations
labels_df = annotations.one_hot_labels_like(clip_df, min_label_overlap=0.25, classes=None)
```
