### ISSUE TITLE
Audio & annotation files not matching up

### ISSUE THREAD

**Issue by carlybatist** [kitzeslab/opensoundscape#519]
I am trying to follow the online documentation here: http://opensoundscape.org/en/latest/tutorials/annotation_tutorial.html and paid up audio & annotation files. However, they aren't matching up correctly because of the extra '.selections' in the annotation file names, so I end up with output that looks like the attached pic. The code I'm using is below, but I copied it directly from the OpSo website. 

<img width="937" alt="Screen Shot 2022-08-06 at 4 01 42 PM" src="https://user-images.githubusercontent.com/46716228/183268504-2aeb6c86-fb9a-4940-911c-cf50ae8879c4.png">

from opensoundscape.audio import Audio
from opensoundscape.spectrogram import Spectrogram
from opensoundscape.annotations import BoxedAnnotations
from opensoundscape.helpers import generate_clip_times_df
from pathlib import Path
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
from glob import glob

#set directory to find .wav and .txt files
raven_files_dir = '/Users/carlybatist/Documents/CV4Ecology/Practice'
audio_files_dir = '/Users/carlybatist/Documents/CV4Ecology/Practice'

#find all audio/txt files files
raven_files = glob(f"{raven_files_dir}/*.selections.txt")
print(f"found {len(raven_files)} annotation files")
audio_files = glob(f"{audio_files_dir}/*.wav")+glob(f"{audio_files_dir}/*.WAV")
print(f"found {len(audio_files)} audio files")
print(raven_files)
print(audio_files)

#pair up the raven and audio files based on the audio file name
audio_df = pd.DataFrame({'audio_file':audio_files})
audio_df
audio_df.index = [Path(f).stem for f in audio_files]
raven_df = pd.DataFrame({'raven_file':raven_files})
raven_df
raven_df.index = [Path(f).stem.split('.Table')[0] for f in raven_files]
paired_df = audio_df.join(raven_df,how='outer')
paired_df

**Comment by sammlapp** [comment]
Hi @carlybatist, sometimes you will need to do a bit of manual parsing of file names based on the file naming convention of files on your computer. In this case, you could adjust the code that matches the files by changing the line where you set `raven_df.index` to
```
raven_df.index = [Path(f).stem.split('.Table')[0].replace('.selections','') for f in raven_files]
```

This code simply removes the ".selections" part of the file name from the index so that the indices will match. 

You can re-open this issue if there is a problem with the code or documentation beyond adjusting the file name parsing.

**Comment by louisfh** [comment]
Hi Carly - I see Sam's already closed the issue. The problem you're having is matching the names of the annotation files to the names of the audio files to create a dataframe. This is actually not an OpenSoundscape issue so it might be helpful to take a look at the documentation of Pandas to understand what's going on in the code from the tutorial. If the naming convention of your files is different to the naming convention in our tutorial, the code won't work without you having to make some changes.
