### ISSUE TITLE
Struggling to load models saved in 0.6.x

### ISSUE THREAD

**Issue by lydiakatsis** [kitzeslab/opensoundscape#524]
I'm trying to follow the instructions in the tutorial to save the weights from a model trained in 0.6.x and then reload in 0.7, but the keys don't match, and consequently the weights wont load.

**Comment by sammlapp** [comment]
It seems the issue was related to using `model.load()` instead of `load_model`. Confusingly, `model.load()` actually does nothing in opso 0.6.x and 0.7.x, so I've opened a new issue #526 to resolve that. 

I'll close this issue, but feel free to re-open it with more details if any issues remain.
