### ISSUE TITLE
Fix BoxedAnnotation.one_hot_labels_like() handling of empty selection tables when a class is specified

### ISSUE THREAD

**Issue by rhine3** [kitzeslab/opensoundscape#528]
Caveat for this whole issue--`classes=None` here means something specific that might be changed in addressing #510.

Sometimes one uses `BoxedAnnotation.one_hot_labels_like()` for a set of annotation files where some files don't contain annotations.

When `BoxedAnnotation.df` contains annotation rows, using `BoxedAnnotation.one_hot_labels_like()` with `classes=None` produces a DataFrame that looks like this for every class that is provided in the annotation columns (e.g. "EATO"):
```
file, start_time, end_time, EATO
filenameA_0.0s_3.0s.wav, 0.0, 3.0, 0
filenameA_3.0s_6.0s.wav, 3.0, 6.0, 1
etc.
```

And you can even do this for classes that aren't provided in the annotation columns (e.g.  classes=["EATO, "ACodeThatNobodyAnnotated"]):
```
file, start_time, end_time, EATO, ACodeThatNobodyAnnotated
filenameA_0.0s_3.0s.wav, 0.0, 3.0, 0, 0
filenameA_3.0s_6.0s.wav, 3.0, 6.0, 1, 0
etc.
```

But when `BoxedAnnotation.df` does not have annotation rows, i.e. is an empty DataFrame that was loaded from a Raven selections file without rows:
```
Selection, View, annotation, start_time, end_time, low_f, high_f
```

then `BoxedAnnotations.one_hot_labels_like()` with argument `classes=None` gives the following output, a DataFrame with a single column called “file” and no annotation column:
```
file, start_time, end_time
filenameB_0.0s_3.0s.wav, 0.0, 3.0
filenameB_3.0s_6.0s.wav, 3.0, 6.0
```

This behavior makes sense, since there was no annotation column, after all--but it should be more clearly described in the documentation (see context/ suggestions below).

However, the code throws an error if you *do* try to do the right thing and be explicit about classes while your selection table is empty:

```
#annotations.df is a dataframe with no rows that has these columns:
#Selection, View, annotation, start_time, end_time, low_f, high_f

annotations.one_hot_labels_like(clip_df, classes=["ACodeThatNobodyAnnotated"], min_label_overlap=min_label_overlap, keep_index=True)
```
produces this error:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/opt/anaconda3/envs/opso-dev/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2897             try:
-> 2898                 return self._engine.get_loc(casted_key)
   2899             except KeyError as err:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'start_time'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
/var/folders/t6/c2h76xs16cn4jt3vqc68b5lm0000gr/T/ipykernel_51460/777806471.py in <module>
----> 1 annotations.one_hot_labels_like(clip_df, classes=[1, "ACodeThatNobodyAnnotated"], min_label_overlap=min_label_overlap, keep_index=True)

~/Code/opensoundscape/opensoundscape/annotations.py in one_hot_labels_like(self, clip_df, classes, min_label_overlap, min_label_fraction, keep_index)
    319 
    320         for (start, end), _ in clip_df.iterrows():
--> 321             clip_df.loc[(start, end), :] = one_hot_labels_on_time_interval(
    322                 df,
    323                 start_time=start,

~/Code/opensoundscape/opensoundscape/annotations.py in one_hot_labels_on_time_interval(df, classes, start_time, end_time, min_label_overlap, min_label_fraction)
    508     df.loc[:, "overlap"] = [
    509         overlap([start_time, end_time], [t0, t1])
--> 510         for t0, t1 in zip(df["start_time"], df["end_time"])
    511     ]
    512 

~/opt/anaconda3/envs/opso-dev/lib/python3.8/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2904             if self.columns.nlevels > 1:
   2905                 return self._getitem_multilevel(key)
-> 2906             indexer = self.columns.get_loc(key)
   2907             if is_integer(indexer):
   2908                 indexer = [indexer]

~/opt/anaconda3/envs/opso-dev/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2898                 return self._engine.get_loc(casted_key)
   2899             except KeyError as err:
-> 2900                 raise KeyError(key) from err
   2901 
   2902         if tolerance is not None:

KeyError: 'start_time'
```

Not sure why this throws a KeyError. Maybe it's related to the context of me using the Channel column as an annotation column as a workaround (see below/#510). In any case, the behavior of this should be to create the following DataFrame:

```
file, start_time, end_time, ACodeThatNobodyAnnotated
filenameA_0.0s_3.0s.wav, 0.0, 3.0, 0
filenameA_3.0s_6.0s.wav, 3.0, 6.0, 0
etc.
```

---

Context/documentation suggestions: 

This issue originally arose when I was using the `Channel` column as an "annotation" column as a workaround for issue #510, working with data without an annotation column because only a single class was being annotated. By using `classes=None` I expected that all of the dataframes produced by `BoxedAnnotations.one_hot_labels_like()` would have a single annotation column, `1`, because all of the files had that Channel number. 

When I tried to concatenate all these DataFrames, I got an error because some of the files had no annotation rows, and hence, no column called `1`. Then, when I instead tried to be explicit about what classes to use so that all of the dataframes would have the same annotation columns and would concatenate correctly, I ran into the error above for empty annotation files.

I suggest adding a small section in the Annotation documentation that describes this potential confusion and gives two examples of how to avoid this issue:
* use an annotation dataset where not all files have the same annotations in them. For instance, all files may contain an EATO but only a couple files contain a CERW. Use `one_hot_labels_like(classes=None)` in a loop to append to a list of annotation dataframes, so that all dataframes in the list have an EATO column, but only some dataframes have a CERW column. Then, demonstrate the use of a Pandas function to correctly join these into one large DataFrame that contains both EATO and CERW as columns, where the CERW columns are correctly populated with 0s.
* an example where you figure out all the classes that are in your dataset and then be specific about `classes=['all', 'my', 'classes']` (this obviously only works if the bug above is fixed for empty files)

**Comment by jatinkhilnani** [comment]
Bug for empty files (#548) is fixed with PR #593.
