### ISSUE TITLE
floating point indices of clip dfs don't match

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#529]
For a table of labels or predictions, the indices being floats can be an issue because they might not match perfectly (eg if saved to a file and reloaded)

**Comment by sammlapp** [comment]
@louisfh could you give an example of when this happens?

**Comment by louisfh** [comment]
Here's an example using the files we have in our CNN training demo notebook.

```
import opensoundscape
import pandas as pd
import subprocess 

#download the woodcock example files used in our CNN training demo notebook
subprocess.run(['curl','https://pitt.box.com/shared/static/79fi7d715dulcldsy6uogz02rsn5uesd.gz','-L', '-o','woodcock_labeled_data.tar.gz']) # Download the data
subprocess.run(["tar","-xzf", "woodcock_labeled_data.tar.gz"]) # Unzip the downloaded tar.gz file

# make list of audio files
files = pd.read_csv("./woodcock_labeled_data/one_hot_labels.csv", index_col =0)
files = ["./woodcock_labeled_data/" + f for f in files.index]

model = opensoundscape.torch.models.cnn.CNN('resnet18', classes = ["positive", "negative"], sample_duration=0.2)
preds = model.predict(files)[0]
preds.to_csv("preds_df.csv")
read_preds = pd.read_csv("preds_df.csv", index_col = [0,1,2])

#count how many problems caused
indices_match = 0
indices_dont_match = 0
for i in preds.index:
    try:
        read_preds.loc[i]
        indices_match +=1
    except KeyError:
        indices_dont_match += 1
```

On my machine the loop at the bottom shows I get 58 KeyErrors, caused by floating point discrepancies.

**Comment by louisfh** [comment]
Another example of the issues caused by this. It feels like you should be able to access e.g. 
`preds.loc[("./woodcock_labeled_data/d4c40b6066b489518f8da83af1ee4984.wav", 1, 1.2)]` works
but:
`preds.loc[("./woodcock_labeled_data/d4c40b6066b489518f8da83af1ee4984.wav", 1.2, 1.4)]` raises KeyError

**Comment by sammlapp** [comment]
From experimentation, it seems like if we just round clip start/end times to, say, 10 decimal places when we create them, we avoid this issue. Even saving/reloading the table or adding a value like 1.5 and searching for the updated value in the index seems to work ok.
