### ISSUE TITLE
document how to create BoxedAnnotations from a dataframe of start and end times

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#530]
Sometimes we manually create dataframes because extra parsing of Raven files is required. What is the method to generate a BoxedAnnotation object from the pandas dataframe? 

- should document the init method BoxedAnnotations(df=...)

**Comment by jatinkhilnani** [comment]
Seemed to have sufficient documentation, I updated it for clarity and removal of typos in #594
