### ISSUE TITLE
update black minimum version

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#538]
I have an error with black v 19.3b0 `ImportError: cannot import name '_unicodefun' from 'click'`

It's resolved by updating black to >=22.3.0, so we should update dev requirements to require newer black.

Unfortunatly, each time we change the black package version, it can change how it wants opso code to be formatted. We should pick a static version of black again, eg 22.8.0, and use it as long as possible. We should have a single commit to develop which applies the new black's formatting across the code base.

**Comment by sammlapp** [comment]
@jatinkhilnani pointed out that Black is "stable" (22.8.0 [release notes](https://black.readthedocs.io/en/stable/)), which might mean that updated or non-equivalent black versions won't cause problems. 

Based on the [stability policy](https://black.readthedocs.io/en/stable/the_black_code_style/index.html#stability-policy) it seems like we should use a requirement like `black ~= 22.0` where we can update "22" to the calendar year ([which allows](https://python-poetry.org/docs/dependency-specification/#tilde-requirements) versions >=22.0<22.1)

**Comment by jatinkhilnani** [comment]
Quick clarification `black ~= 22.0` is meant to allow >= 22.0, <23.0 that is == 22.*
It is not clearly evident from poetry's [Dependency Specification](https://python-poetry.org/docs/dependency-specification/#tilde-requirements) page, hence we need to double check.

**Comment by jatinkhilnani** [comment]
So dependency set as `black ~= 22.8` through this fix should work for this year.
