### ISSUE TITLE
Audio Metadata - extension to #446 & #523

### ISSUE THREAD

**Issue by jatinkhilnani** [kitzeslab/opensoundscape#555]
Some points to discuss and resolve for generic metadata template.
- Recording start time should be readable string in standard format vs currently saved `datetime` object
- Change `audiomoth_id` to `device_id`

**Comment by sammlapp** [comment]
can you elaborate by providing examples from existing metadata and the proposed change?

**Comment by sammlapp** [comment]
For now, let's just change the field name to device_id

**Comment by sammlapp** [comment]
unfortunately we can't save metadata in non-standard fields, so we can't create a field for recording start time and save a string-formatted date time in it. For now, we will retain the comment field such that it can be re-parsed if the file is loaded again. However, note that if an audio file is trimmed, we can't save an updated start time to match the beginning of the trimmed file.

**Comment by sammlapp** [comment]
We might want to allow writing updated metadata fields in a comment string 
```
a = Audio.from_file('audiomoth.wav')
a.metadata['temp']
a.metadata['recording start time']
a.trim(60*60,2*60*60)

a.save(

comment="{temp:0,param:1,recording start time: }"
)
```
