### ISSUE TITLE
Cryptic error when all samples fail to preprocess

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#562]
If all samples fail to preprocess when running model.predict() or model.train() the user will see "IndexError: Tried all samples, none were safe" but won't see the underlying errors because they are caught by SafeDatasets. Maybe we should have a flag for raising rather than catching preprocessing errors, or some other way to see the underlying errors when samples fail to preprocess.

**Comment by louisfh** [comment]
Maybe have a flag that will tell the preprocessor to raise the errors or

**Comment by louisfh** [comment]
We should have a `raise_exceptions` argument, this will be a boolean that will change the default behavior of safe dataset. This should be implemented for both train and predict.
