### ISSUE TITLE
Making Sound Clips

### ISSUE THREAD

**Issue by quietlight** [kitzeslab/opensoundscape#598]
Hi
Apologies for taking time of busy people. I am trying to make bulk sound clips but the for loop seems to conclude after 538 files instead of over a million. Python is not my strong point, I spend my time in Julia, but your work can help my project a lot. 

Find my static project pluto notebook here: [skraak.kiwi](https://skraak.kiwi), I have terrabytes of data from a small island.

Failed Jupyter notebook here:
[MakeClips1-onlydidfirst538clips.zip](https://github.com/kitzeslab/opensoundscape/files/10179590/MakeClips1-onlydidfirst538clips.zip)

This data set is pretty consistent, my files are labelled in AviaNZ which produces json label files, I culled 6091 15 minute files containing kiwi calls and rewrote the labels into raven files consistent with your example.

I need to train a binary classifier for haast tokoeka (kiwi), avianz gets around 20-40% true positives with a model trained for the Dept of Conservation, and the training interface is broken. I will later train a recogniser for my labels to save me work. M/F/MF/?, Near/Mid/Far, Noise, and possibly auto detect duets.

I add data at almost 1TB/month so have to get organised with a better recogniser.

I like the simple modular and extensible approach this project takes, also it does not lock me in, I can use my own tools written in Julia.

So the big problem for me here: why is that for loop dying?

Regards
David Cary

Ok, it is obvious when you look. Sorry for wasting time

**Comment by sammlapp** [comment]
I'm glad you found a resolution, don't hesitate to post questions about the code base or reach out with other questions in the future.
