### ISSUE TITLE
Beginner friendly training and prediction with CNNs

### ISSUE THREAD

**Issue by quietlight** [kitzeslab/opensoundscape#601]
Hi

The preprocessing pipeline in your article assumes a sample rate of 44100. If your data is at 16000 as  most of mine is, or 8000 as a small amount of mine is, the pipeline fails. The problem is with bandpass, bounds error.  You  need model.preprocessor.pipeline.bandpass.bypass=True or it will fail.

Try your own example but with downsampled woodcock data and it  will fail.

Best to  be clear about assumptions in the documentation. Saves everyones time.

Thanks for sharing though. I finally have something training. 

Regards
David

**Comment by sammlapp** [comment]
Thank you for sharing. I have added a caveat in the documentations and it will be included in the next release
