### ISSUE TITLE
Add tutorial for training CNN on unsplit audio + raven annotations 

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#654]
Tutorials should show how to train and predict on a dataframe with multi-index of 'file','start_time','end_time'

a good tutorials would be to show loading of a Raven annotation table, creating one-hot clip labels, perhaps subsetting clips, and training a CNN

**Comment by sammlapp** [comment]
see #730 for example of how to do it

**Comment by rhine3** [comment]
The revamped "train a CNN" tutorial now focuses on an example training from Raven files (added in 09e7b005742f60a9b4fbf435afd8b0da3e92717b)! 

This is updated in develop and will be merged into the master docs with the next release.
