### ISSUE TITLE
Poetry Lock file missing pillow wheel build

### ISSUE THREAD

**Issue by louisfh** [kitzeslab/opensoundscape#657]
When using poetry to install Opensoundscape in a new environment on Mac OSX - I get an error. This is because the Poetry.lock file that contains the hashes of appropriate wheel files for each package, does not contain all possible wheels. In particular - after running `poetry install` I get the below error:

```
Command ['/opt/anaconda3/envs/poetry_py39/bin/python', '-m', 'pip', 'install', '--no-deps', '--no-input', '-r', '/var/folders/_s/zm3gz4x52glfbflc25_3rp3w0000gq/T/pillow-9.4.0j4f17n8freqs.txt'] errored with the following return code 1, and output: 
Collecting pillow==9.4.0
  Using cached Pillow-9.4.0-2-cp39-cp39-macosx_10_10_x86_64.whl (3.3 MB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    pillow==9.4.0 from https://files.pythonhosted.org/packages/9e/73/4aacfaeee07328835131683c27d8246b50b10260ff30982e5d988d04e06f/Pillow-9.4.0-2-cp39-cp39-macosx_10_10_x86_64.whl (from -r /var/folders/_s/zm3gz4x52glfbflc25_3rp3w0000gq/T/pillow-9.4.0j4f17n8freqs.txt (line 1)):
        Expected sha256 0845adc64fe9886db00f5ab68c4a8cd933ab749a87747555cec1c95acea64b0b
...
```

This was not solved after deleting the pip and poetry caches. I think is is because the hash for this particular wheel of pillow: `Pillow-9.4.0-2-cp39-cp39-macosx_10_10_x86_64.whl`, did not have its hash in the poetry lock file. To install Opensoundscape I had to create a new poetry lock file and then poetr install:
```
poetry lock --no-update
poetry install
```

Adding this issue to document the solution for other users.

**Comment by sammlapp** [comment]
During the release of 0.9.0 I could not run `poetry lock`, it just ran forever. `poetry lock --no-update` worked, but I think we'd like to run `poetry lock`. One thing to try is to require higher versions of packages in pyproject.toml, which might make solving the environment easier?

**Comment by sammlapp** [comment]
this issue is resolved, I don't remember exactly in which commit/PR, but we resolved the hanging poetry lock and we can now run `poetry lock` before each release. This is now part of our release protocol
