### ISSUE TITLE
Comment code

### ISSUE THREAD

**Issue by rhine3** [kitzeslab/opensoundscape#68]
Add high-level comments in literate programming style, a la Donald Knuth. Comments should enable users to skim code. This includes both descriptive comments at the function level (but outside of docstrings), and line-by-line comments for weird or challenging-to-understand code (e.g. "This block reshapes the feature data to X dimension for Y reason").

**Comment by chiroptical** [comment]
We need to rewrite many of the comments using Sphinx syntax. Tutorial: https://matplotlib.org/sampledoc/

**Comment by jkitzes** [comment]
Not sure if this belongs here, but I'm going to suggest that we do our higher level documentation using ReadTheDocs rather than Sphinx. Doesn't mean we *shouldn't* format the docstrings in a systematic manner, only that it doesn't necessarily have to be Sphinx-compatible.
