### ISSUE TITLE
SpatialEvent Class inconsistencies in methods.

### ISSUE THREAD

**Issue by louisfh** [kitzeslab/opensoundscape#705]
When you estimate the position of a soundsource using `SpatialEvent.estimate_location(cc_threshold=..)` you can pass a cc_threshold. This filters the tdoas by their cross-correlation score, and only uses the tdoas whose corresponding `cc_max > cc_threshold` for localization. The intention is that we can throw away tdoas that might be spurious. 

However the other methods don't use a cc_threshold. This means for example that the `distance_residual` returned by `SpatialEvent.calculate_residual_rms` is calculated on all tdoas, not just those that are above `cc_threshold`. 

e.g.
```
event = SpatialEvent(...cc_threshold=0.1) # imagine the cc_maxes = [0.02, 0.02, 0.02, 0.11, 0.11, 0.11]
estimated_locaiton = event.estimate_position()
tdoa_residuals = event.calculate_distance_residuals()
```
It's misleading that there will be 6 tdoa_residuals, but in fact only 3 TDOAs were used for localization. If we're discarding tdoas with low cc_max for localization, we should not then use them for calculating our tdoa_residuals.

**Comment by louisfh** [comment]
A solution would be to have only a single method `estimate_location`. This must be passed an argument of`cc_threshold`. In the call to this method, the attribute `self.distance_residuals` and `self.distance_residuals_rms` would be written to. We should also ensure that the attribute `self.cc_threshold` is written to when this method is called, so that the attribute always refers to the cc_threshold actually used for localization, and does not get 'out of sync'.

**Comment by sammlapp** [comment]
Good point. What if `calculate_distance_residuals` was just a function in the module, rather than a method of SpatialEvent. Then you are forced to pass it the list of
