### ISSUE TITLE
add documentation for using Google Colab in "installation"

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#718]
Users that just want to try OpenSoundscape or prefer not to install it locally can use Google Colab. However, sometimes Google Colab causes issues, so we should document how to use it. (For instance, it now uses python 3.10.0 which is technically not supported by opensoundscape - but it can still run by ignoring the python requirement with --ignore-requires-python)

**Comment by charleygros** [comment]
> but it can still run by ignoring the python requirement with --ignore-requires-python

Agreed, this worked well for me.

```
!pip install opensoundscape==0.9.0 --ignore-requires-python
```

**Comment by sammlapp** [comment]
FYI, OpenSoundscape's develop branch no longer has Python<3.10 (this will be merged into master and apply to future releases starting with 0.9.1) which means installing in colab with `!pip install opensoundscape` should not cause any issues (once OpenSoundscape version 0.9.1 is released)
