### ISSUE TITLE
consider using online files in tutorials

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#720]
`Audio` class now has `from_url` method. Instead of requiring a local file, tutorials (especially those just using one file) could access an online file. (On the other hand, this would mean the tutorial would not work offline).

**Comment by syunkova** [comment]
We could make a commented-out option for those using the tutorial offline? But AFAIK the "local" file still typically needs to be downloaded at the start of the tutorial

**Comment by sammlapp** [comment]
We can use a xeno canto file like this:
```
Audio.from_url(f'https://xeno-canto.org/818024/download')
```

**Comment by syunkova** [comment]
@sammlapp didn't get a chance to bring it up earlier but I've been looking at this issue more today and I'm still not sold on adding an "online" option for two reasons:
1) leaving both from_file and from_url commands (even if, say, we specified off/online first & added if statements) would require some user input, which adds complexity to the tutorials that may be already confusing for beginner users.
2) in some of the tutorials, we use from_file several times- so I wonder if re-downloading the file every time could slow down the tutorial? Though in this case, we could just load the audio once and change the remaining statements to use that.
If we wanted to use from_url at some point while also keeping a local file, could try doing something like Audio.from_url('.......').save('......') ?
