### ISSUE TITLE
Make SPEED_OF_SOUND a class attribute instead of module/global variable

### ISSUE THREAD

**Issue by louisfh** [kitzeslab/opensoundscape#725]
I think instead of declaring the variable SPEED_OF_SOUND in the localization module, we should set it as an attribute of `SynchronizedRecorderArray` and `SpatialEvent`. We can have default values of 343 m/s. 

I think this would make it easier for people to adjust the speed_of_sound if they are performing localization in another medium (e.g. marine), or want to adjust the SPEED_OF_SOUND based on humidity/temperature/elevation.

**Comment by sammlapp** [comment]
The reason it’s a module level global variable is that I think it should only be defined in one place. Would get and set functions for the module resolute your concern?

**Comment by louisfh** [comment]
That's a good point. Functions outside of our classes (`localize`, `calculate_tdoa_residuals`) require a speed_of_sound argument and its helpful to define a default in one place for those. I guess get and set functions would work.

Alternatively, we could:
- Make the user set speed_of_sound when initializing SynchronizedRecorderArray
- SpatialEvents will then be initialized by the SyncrhonizedRecorderArray with the same speed_of_sound.
- Enforce that methods of SynchronizedRecorderArray and SpatialEvent always use self.speed_of_sound.

The risk with the second approach (which I guess is what you were trying to avoid) is if in the code base we accidentally pass SPEED_OF_SOUND to a method, instead of self.speed_of_sound, or forget to pass a speed_of_sound value and it defaults to SPEED_OF_SOUND.

**Comment by sammlapp** [comment]
Stepping back, would it make more sense for each SpatialEvent to have a temperature and humidity that are used to calculate speed of sound?

**Comment by sammlapp** [comment]
(and medium / density, ie air / water)
