### ISSUE TITLE
signal_processing.tdoa redefines 'signal' in function scope

### ISSUE THREAD

**Issue by louisfh** [kitzeslab/opensoundscape#734]
Our `signal_processing.tdoa` function has the first argument called `signal`.
Earlier in `signal_processing` module we assign `signal` to the scipy.signal module with `from scipy import signal`.

It's probably bad practice to do this. We should change the name of the argument, or the import. I think it would be clearer if we changed our import to just `import scipy` and for every function used `scipy.signal....`

**Comment by sammlapp** [comment]
resolved in #738
