### ISSUE TITLE
Annotation column selection in BoxedAnnotations.from_raven_files

### ISSUE THREAD

**Issue by syunkova** [kitzeslab/opensoundscape#735]
BoxedAnnotations.from_raven_files can take a parameter indicating the "id" of the annotation column. Currently it takes the zero-based position of the column - like, for a Raven file with 6 columns where the fifth one contains annotations, one would need to set annotation_column_idx to 4 to extract the annotations properly. Could it be more intuitive to ask for the "non-programming" order number of the column?
Additionally, perhaps it could be beneficial to reallow the ability to pick out the annotation column by its name?

**Comment by syunkova** [comment]
Another thought: when annotations are done by multiple people, some may end up containing extra columns while others don't; as of now, the method throws a KeyError if the user wants to keep an extra column that is not present in every annotation file in the file list. Would it be beneficial to instead still allow the extra column, but leave cells empty/null for files that don't contain the column?

**Comment by sammlapp** [comment]
I implemented it so that if you pass `annotation_column_name`, it ignores `annotation_column_idx`. This is not optimal because it would be confusing to the user if they try to pass both, but is the cleanest implementation. The docstring clearly describes the behavior.
