### ISSUE TITLE
Add support for another AudioMoth metadata formatting

### ISSUE THREAD

**Issue by syunkova** [kitzeslab/opensoundscape#745]
For some reason some older AudioMoths have a slightly different comment field format than what the aru module accounts for: instead of "Recorded at ____ by AudioMoth #### ..." it looks like "Recorded at _____ during deployment #### ..." (with the serial number of the device after _deployment_). Though they don't come up often, audios from these "weird format" AMs don't get custom metadata fields as the datetime can't be parsed with the current code, and so the comment can't either. It could be useful to support this metadata format as well. Additionally, maybe we should consider still allowing other parameters to be parsed if one can't (e.g. if the comment field is missing a device ID, still get gain&temperature etc)?

**Comment by sammlapp** [comment]
Are you sure this is due to older audiomoth version, rather than an older firmware? Generally each firmware creates a consistent metadata format. Can you check the audiomoth version and firmware version for the files that caused errors?

Robustness to one error is tricky but might be possible. We are parsing the comment string in a pretty fragile way.

**Comment by sammlapp** [comment]
also please provide a full copy of the metadata, that will assist with implementing a working parser

**Comment by syunkova** [comment]
@sammlapp it probably is firmware! Sadly I don't have the full metadata and don't remember which card the issue came up for but will look for it
The warning message was:
`UserWarning: This seems to be an AudioMoth file, but parse_audiomoth_metadata() raised: unconverted data remains:  during deployment 41C351E84E9996C2 at medium gain setting while battery state was 4.6V and temperature was 4.7C.`

**Comment by syunkova** [comment]
Here's a full copy of the metadata from a file that raised this warning:

> {'artist': 'AudioMoth 243B1F075C7B4301',
>  'comment': 'Recorded at 10:00:00 15/05/2021 (UTC) during deployment 41C351E84E9996C2 at medium gain setting while battery state was 4.7V and temperature was 3.7C.',
>  'samplerate': 32000,
>  'format': 'WAV',
>  'frames': 230400000,
>  'sections': 1,
>  'subtype': 'PCM_16',
>  'channels': 1,
>  'duration': 7200.0}

Strange that it's the same deployment "id" but a different card and ARU from before... Also, pretty sure the firmware version was 1.5, for which the typical comment field would say "Recorded at --- by AudioMoth".

**Comment by sammlapp** [comment]
It looks like `deployment ###` is not the serial number of the device, but some different piece of information. However, we can resolve the brittle-ness of the parser by not requiring the next word to be "by"
