### ISSUE TITLE
Crowsetta integration

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#749]
The [crowsetta](https://github.com/vocalpy/crowsetta) package provides and continually adds support for parsing various annotation formats. The `annotation` modules should support integration with classes from `crowsetta`, possibly using `crowsetta` classes within the `BoxedAnnotations` class (or subsetting) or at a minimum, `from_crowsetta` and `to_crowsetta` options. 

Note that BoxedAnnotations now supports content from multiple files, while I think the crowsetta objects are designed to hold annotations from a single annotated file.

**Comment by sammlapp** [comment]
David Nicholson suggested that Crowsetta is designed to be used "under the hood", ie could be used within methods of BoxedAnnotations to load various annotation formats - rather than requiring users to interact with the crowsetta API directly. This makes sense to me, and suggests we should refactor the PR (https://github.com/kitzeslab/opensoundscape/pull/764) to have an API more like `BoxedAnnotations.from_file(...)` which uses the crowsetta API under the hood

**Comment by paulpeyret-biophonia** [comment]
Hello @sammlapp 
I would love to see this new feature happening. I think we are legion in the bioacousticians community using Audacity instead of Raven for our manual annotations. Crowsetta would nicely fulfill the need for audacity marker files import.
I have seen some development have been happening here #764 

Is this feature still under development?

Thanks a lot,

**Comment by sammlapp** [comment]
Hi @paulpeyret-biophonia, I paused this due to the active development of [soundevent](https://github.com/mbsantiago/soundevent), which could provide a flexible universal annotation class. However, it will be easy enough to add these crowsetta integrations implemented in #764. Would the functionality implemented there (BoxedAnnotations:  .from_crowsetta, .from_crowsetta_bbox, and from_crowsetta_sequence, as well as export versions) be sufficient for your use case?

**Comment by paulpeyret-biophonia** [comment]
Hi @sammlapp 
Thanks for you answer. I didn't know about this new package! That's sounds great! I will keep myself posted on this one.
Yes the implementation you proposed would be perfect! 
Thanks

**Comment by NickleDave** [comment]
Not to add noise to this issue, but @paulpeyret-biophonia if you have any feedback on how easy it is to work with your Audacity annotations using crowsetta, I'd love to hear it. Please feel free to tag me into a convo if you run into issues loading your annotations with SoundEvent via crowsetta (and you can also raise issues on the crowsetta repo directly or start a discussion in [our forum](https://forum.vocalpy.org/) if you'd like)
