### ISSUE TITLE
Change the way 'edge of audio' in the localization pipeline is handled

### ISSUE THREAD

**Issue by louisfh** [kitzeslab/opensoundscape#751]
If you flag a detection at the beginning or end of audio, and try and estimate the TDOA between receivers, the localization pipeline will raise a ValueError. This is because we aren't able to estimate the TDOA using cross-correlation at the 'edges' of the audio file.

Instead of raising an exception, we should handle this more cleverly or simply raise a warning that the TDOA estimated may be incorrect when the `estimate_position`/ `estimate_location` (renamed in branch) method is called on a SpatialEvent that occurs at the edge of an audio file.

**Comment by sammlapp** [comment]
I actually think it makes sense to not attempt to localize these edge cases, we could give the user a warning letting them know it got skipped.

**Comment by sammlapp** [comment]
@louisfh confirm this is resolved based on merging #783 ?
