### ISSUE TITLE
Raven file not retained in BoxedAnnotations if keep_extra_columns=False

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#769]

**Comment by syunkova** [comment]
Adding note that this also occurs if a list of columns is passed to keep_extra_columns.

**Comment by syunkova** [comment]
Should be solved just by moving L158 df["raven_file"] = raven_file to the bottom of the from_raven_files method ?

**Comment by sammlapp** [comment]
@syunkova open a pull request if you have a branch that fixes the issue
