### ISSUE TITLE
ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmp1k41qlgewandb'>

### ISSUE THREAD

**Issue by louisfh** [kitzeslab/opensoundscape#775]
I keep seeing this Warning. This happens even in scripts where I am not training or using a model, so I don't understand why temp files that appear to be related to wandb are being created.

Here's the full warnings:
```
/home/lfh/miniconda3/envs/opso_091_pip_py39/lib/python3.9/tempfile.py:821: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmp1k41qlgewandb'>
  _warnings.warn(warn_message, ResourceWarning)
/home/lfh/miniconda3/envs/opso_091_pip_py39/lib/python3.9/tempfile.py:821: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmp0wolavyawandb-artifacts'>
  _warnings.warn(warn_message, ResourceWarning)
/home/lfh/miniconda3/envs/opso_091_pip_py39/lib/python3.9/tempfile.py:821: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpv7paddovwandb-media'>
  _warnings.warn(warn_message, ResourceWarning)
/home/lfh/miniconda3/envs/opso_091_pip_py39/lib/python3.9/tempfile.py:821: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpghepu6pzwandb-media'>
  _warnings.warn(warn_message, ResourceWarning)
```

**Comment by sammlapp** [comment]
this seems related https://github.com/wandb/wandb/issues/5258

**Comment by sammlapp** [comment]
the issue hasn't been resolved but there's now a workaround https://github.com/wandb/wandb/issues/5258#issuecomment-1897623369 and recent activity

**Comment by sammlapp** [comment]
Ah the issue is now closed as resolved, an updated wandb dependency should fix this (as soon as there’s a new wandb release)

**Comment by sammlapp** [comment]
@louisfh can you confirm that this is fixed if we update the wandb dependency?

**Comment by louisfh** [comment]
I'm no longer able to reproduce this behavior with wandb 0.17.7 (version in poetry lock file currently). I assume this has been fixed. Closing the issue and we can reopen if it reappears.
