### ISSUE TITLE
DeprecationWarning when calling Spectrogram.plot()

### ISSUE THREAD

**Issue by louisfh** [kitzeslab/opensoundscape#777]
```
/opt/anaconda3/envs/pip_opso091_py310/lib/python3.10/site-packages/matplotlib_inline/config.py:68: DeprecationWarning: InlineBackend._figure_format_changed is deprecated in traitlets 4.1: use @observe and @unobserve instead.
  def _figure_format_changed(self, name, old, new):
```

**Comment by sammlapp** [comment]
@louisfh can you provide a reproducible example? 

I think it might be related to using `%config InlineBackend.figure_format = 'retina'`

I suspect that it may be fixed in a newer matplotlib version, so we might just need to update the minimum version requirement of matplotlib
