### ISSUE TITLE
Raise warning when CNN.load_model() is used for a model object was saved in a different OpenSoundscape version

### ISSUE THREAD

**Issue by louisfh** [kitzeslab/opensoundscape#779]
When using `CNN.load_model` we should verify that the model was saved using the same version of OpensoundScape. We should then raise a warning if it was not, that explains `CNN.from_torch_dict` should be used.

This might be annoying to implement, as at present saved model objects are just pickled, and so will probably just throw an error when trying to load them.

**Comment by sammlapp** [comment]
@louisfh how about a helpful error message using a try-catch block? It's not going to be generally possible to load the model object if we get an error like this. Also, in your experience is the exception always a ModuleNotFoundError? 

(implemented an error message with a try catch block in #805 )

**Comment by louisfh** [comment]
I have only seen a ModuleNotFoundError, but I haven't tried all combinations of opensoundscape versions. Maybe more worrying would actually be if an erorr isn't thrown, but there's some different behavior between versions. I think the changes you made in #805 resolve this.
