### ISSUE TITLE
BoxedAnnotations() doesn't create one-hot labels DataFrame for empty Raven selections file

### ISSUE THREAD

**Issue by rhine3** [kitzeslab/opensoundscape#784]
I think that when OpenSoundscape receives a blank annotation file, it should handle it as annotated negatives. For example, we would want one-hot encoded clip labels to include all 0s when a one-hot encoded label dataframe is made from an empty Raven file. However this process doesn't work when combining `BoxedAnnotations.from_raven_files()` with `boxed_annotations.one_hot_clip_labels()`.

When I convert an empty Raven selections.txt file to `BoxedAnnotations` using `BoxedAnnotations.from_raven_files`, I get a DataFrame with no rows containing the columns of a typical BoxedAnnotations DF (audio_file, raven_file, annotation, start_time, end_time, etc.).

Next, when I convert the boxed annotations using `boxed_annotations.one_hot_clip_labels` I get a blank DataFrame with no rows, whereas I'd like to have a `DataFrame` with the typical columns: file, start_time, end_time, and the alpha code of every species I provided in the class_subset, with a 0 for each species. (If `class_subset=None` then this DataFrame would only contain the species columns from the other annotated files that were initially read into `BoxedAnnotations.from_raven_files()`. If there are no species columns, e.g. only blank files were included in the initial BoxedAnnotations, then maybe the dataframe should either have no species columns, or a column of zeroes?)

I think one API for achieving the correct behavior could be providing the recording length to `one_hot_clip_labels()`  via the `full_duration` argument. But when I try to do that, OPSO throws a ValueError. This API would be brittle, because it doesn’t naturally handle empty recordings of different durations, whereas the code to create one hot clip labels does naturally handle annotated recordings of different durations thanks to `BoxedAnnotations.from_raven_files()`.  (And also, I wouldn’t have known to add the “full_duration” argument since no warning was raised that I had an empty BoxedAnnotations dataframe)

You can replicate this behavior with this code using an empty Raven file:
```
boxed_annotations = BoxedAnnotations.from_raven_files(
        ['/bgfs/jkitzes/ter38/data/pnre_annotated_data/annotations/MSD-0003_20180427_5minstart00_00.Table.1.selections.txt'],
        ['/bgfs/jkitzes/ter38/data/pnre_annotated_data/recordings/MSD-0003_20180427_5minstart00_00.wav'])

small_label_df = boxed_annotations.one_hot_clip_labels(
    clip_duration=clip_duration,
    clip_overlap=clip_overlap,
    min_label_overlap=min_label_overlap,
    class_subset=["EATO", "REVI"],
    final_clip=final_clip,
)
```

Similar behavior happens if you provide OPSO with a second annotation file, even if it has annotations in it, e.g. this code produces a dataframe with only one row, for the non-empty annotation file
```
boxed_annotations = BoxedAnnotations.from_raven_files(
        ['/bgfs/jkitzes/ter38/data/pnre_annotated_data/annotations/MSD-0003_20180427_5minstart00_00.Table.1.selections.txt',
        '/bgfs/jkitzes/ter38/data/pnre_annotated_data/annotations/MSD-0003_20180427_5minstart00_05.Table.1.selections.txt'],
        ['/bgfs/jkitzes/ter38/data/pnre_annotated_data/recordings/MSD-0003_20180427_5minstart00_00.wav',
         '/bgfs/jkitzes/ter38/data/pnre_annotated_data/recordings/MSD-0003_20180427_5minstart00_05.wav'])

small_label_df = boxed_annotations.one_hot_clip_labels(
    clip_duration=clip_duration,
    clip_overlap=clip_overlap,
    min_label_overlap=min_label_overlap,
    full_duration=300,
    class_subset=["EATO", "REVI"],
    final_clip=final_clip,
)
```

**Comment by sammlapp** [comment]
There is code in the current code base that is meant to produce the desired behavior, so we have some sort of logical error that results in the observed behavior (no rows instead of rows for each time-period with 0 for all labels). 

https://github.com/kitzeslab/opensoundscape/blob/09cc583f2f8614b5fabc5a28335ff8274068dea5/opensoundscape/annotations.py#L549
