### ISSUE TITLE
Saving a model in old OpSo version and loading it in new version.

### ISSUE THREAD

**Issue by louisfh** [kitzeslab/opensoundscape#786]
There are no clear instructions for how to load a model saved in 0.8.0, in a 0.9.1 environment. I couldn't immediately work out how to do it.

I also think going forward we should think about how to make it easier for users. This might mean ensuring `load_model("/path/to/object")` has logic handling different cases, for different version of Opensoundscape.

**Comment by louisfh** [comment]
This also raised another problem. We often use 'default' value in our preprocessing values. For example see the params below for the preprocessing step that generates a spectrogram:
 ```
model.preprocessor.pipeline.to_spec.params

> window_type                 hann
> window_samples              None
> window_length_sec           None
> overlap_samples             None
> overlap_fraction            None
> fft_size                    None
> decibel_limits       (-100, -20)
> dB_scale                    True
> scaling                 spectrum
```

I think we should actually specify these values when a preprocessor is instantiated, so that the model object itself contains all the information about the preprocessing pipeline. This would then be an easy thing for us to save as a csv. At present, you have to refer to the source code in order to work out these values actually are.

**Comment by sammlapp** [comment]
From opensoundscape 0.9.1, `CNN.save_torch_dict()` and `.load_torch_dict`

**Comment by sammlapp** [comment]
and make a stable API!

**Comment by sammlapp** [comment]
I'm wondering if we should move back towards saving plain weights files, in the typical pytorch .pt convention (model.newtork.state_dict()), which we will be able to load across opso versions as long as the architecture is equivalent. 

The TensorFlow approach is to have a _folder_ containing a file or two with model info and potentially many checkpoint files. This makes sense as only the checkpoints change epoch-to-epoch (and the optimizer state)
