### ISSUE TITLE
Use config yml file for model training: demo

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#795]
This is considered best practice for ML libraries and allows all the configuration parameters to be located and changed in one file without changing the code.

**Comment by louisfh** [comment]
I strongly endorse this idea, having a `config.py` makes it a lot easier to keep track of things you have changed in your code.

**Comment by sammlapp** [comment]
We discussed that it comes down to whether _users_ should create config files in their _projects_, from which they access values in their scripts, or whether opensoundscape should _internally_ use a config file (eg, creating a CNN object might look like `CNN(config)`, and training might look like `.train(config)` or even `.train()` automatically accessing the config values. I'm not sure whether internal config file use is a good idea, but YOLO V8 is an example of a package that implements this [config file](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/default.yaml) approach.

**Comment by sammlapp** [comment]
Looking at how CNN already uses dictionaries for some parameters (.wandb_logging is a dictionary, .optimizer_params is a dictionary), I feel comfortable with the idea that CNN could have a single .config dictionary, which is either flat or contains these existing dictionaries

**Comment by sammlapp** [comment]
Furthermore, we could write a Preprocessor class that takes a config dictionary to aid in reproducibility of preprocessing settings

**Comment by sammlapp** [comment]
Different libraries implement this in different ways:

- simplest: load a Yaml file as a dictionary

- YOLO v8 implements a [custom](https://github.com/ultralytics/ultralytics/blob/53b4f8c713668eba51be3299358c3c99942dfb66/ultralytics/utils/__init__.py#L139) version of SimpleNamespace, which I think allows attribute-like access to the dictionary from yaml 

- [Chirp](https://github.com/google-research/chirp/blob/main/chirp/inference/configs/raw_soundscapes.py) uses  a .py file with a custom class as config

**Comment by sammlapp** [comment]
we settled on providing a repository or boilerplate project using a config, rather than internally supporting config files in the API

**Comment by sammlapp** [comment]
There's now an example of using a config file with the OpenSoundscape CNN class in the Bioacoustics Cookbook repo: https://github.com/kitzeslab/bioacoustics-cookbook/tree/main/cnn_project_with_config_yml
