### ISSUE TITLE
Add instructions for running tutorial notebooks in CoLab

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#818]
I think people might not know what to do with our tutorial notebooks other than look at them. We should provide specific instructions for running them in CoLab:

- download the .ipynb notebook file (how? go to github?)
- open a new CoLab notebook: visit https://colab.research.google.com/ and select 'Upload' (or Google Drive if you first upload the ipynb to Google Drive)
- add a cell at the top:  (or maybe we should somehow include this in our tutorial notebooks) 
```
!pip install opensoundscape
```
- run cells sequentially

Alternatlively (for step 3), we could add cells to the top of our tutorial notebooks that run pip install opensoundscape, or to do so only if the user is using colab:
```bash
%%bash
[[ ! -e /colabtools ]] && exit  # Continue only if running on Google Colab
# Do Colab-only stuff here
!echo hello
!pip install my_packages
```

(It might simply make sense to just have `pip install opensoundscape` run at the top of every tutorial notebook though? )

**Comment by rhine3** [comment]
I have added a blurb on every tutorial that includes a link and instruction to run the tutorial in Colab.
