### ISSUE TITLE
Consider avoiding using term 'one-hot labels'

### ISSUE THREAD

**Issue by louisfh** [kitzeslab/opensoundscape#823]
Sometimes we use the term 'one-hot labels'. I think this term is used when labels are mutually exclusive/only one label will be present. However we use this in e.g. `annotations.one_hot_clip_labels`, where in fact there can be multiple labels.

e.g. a imagine an `annotation` object from a raven file like this:
| audio_file | raven_file| start_time        | end_time         | annotation|
|:-------:|:-------:|:-------------: |:-------------:|:-------:|
| file1.wav | file1.selections.txt |  1      | 4| GWWA | 
| file1.wav | file1.selections.txt |   2   | 5 |  WOTH |

Calling the method one_hot_clip_labels
```
labels_df = annotations.one_hot_clip_labels(
    full_duration=60, # The duration of the entire audio file
    clip_duration=5, 
    clip_overlap=0,
    class_subset=['GWWA_song'],
    min_label_overlap=0.25,
)
```

Should produce a dataframe like this:

| file | start_time        | end_time         | GWWA | WOTH | 
|:-------:|:-------:|:-------------: |:-------------:|:-------:|
| file1.wav | 0 | 5 | 1 | 1 | 0 | 

Using the term 'one-hot' may be confusing, because these are not one-hot labels.

**Comment by louisfh** [comment]
Maybe we should change the name to `generate_clip_labels` or something else.

**Comment by sammlapp** [comment]
Oh, I didn't realize that. I thought these were called one-hot samples. What is the term for labels encoded by 1 or 0 per class? (As opposed to, say, a list of the classes that are present for a sample)

**Comment by sammlapp** [comment]
but that makes sense given the [origin](https://en.wikipedia.org/wiki/One-hot) of the term "one-hot": `In digital circuits and machine learning, a one-hot is a group of bits among which the legal combinations of values are only those with a single high (1) bit `. I never really thought about it as literally, one bit is hot, the rest are not.

**Comment by sammlapp** [comment]
I was about to say that `binary encoding` might be the term, but according to [this post](https://stackoverflow.com/a/54119850/6591124) sklearn's functions imply the opposite (in sklearn, OneHotEncoder can be multi target while BinaryEncoder cannot)

**Comment by sammlapp** [comment]
`binary_clip_labels` ?

**Comment by sammlapp** [comment]
MultiHot? (sensu https://github.com/google-research/perch/blob/70f26ec60825bf1d85f6e75caf245157c0cb6998/chirp/preprocessing/pipeline.py#L538 )

**Comment by sammlapp** [comment]
let's go with MultiHotLabels / multi_hot_labels / to_muti_hot and provide helpful definitions/examples in docstrings

**Comment by sammlapp** [comment]
resolved in https://github.com/kitzeslab/opensoundscape/pull/1036
