### ISSUE TITLE
TqdmWarning on importing CNN module

### ISSUE THREAD

**Issue by rhine3** [kitzeslab/opensoundscape#859]
It looks like the required versions of jupyter and ipywidgets don't contain a needed widget. When I import CNN:
```
from opensoundscape import CNN
```

The following warning is produced:

```
/Users/tessa/Code/opensoundscape/opensoundscape/ml/cnn.py:18: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm
```

**Comment by sammlapp** [comment]
Upgrading jupyter and ipywidgets does resolve this Warning, but then we get a new warning TqdmExperimentalWarning

**Comment by sammlapp** [comment]
I think that if you have the updated requirements, you actually get the TqdmExperimentalWarning rather than the Iprogress request update.

**Comment by louisfh** [comment]
With the current versions of dependencies (as tested on Google Colab) we get the warning:
```TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm```

I don't think we should do anything about this, as this behavior seems fine to me.
