### ISSUE TITLE
wandb error in Jupyter notebook "TypeError: _WandbInit._resume_backend() takes 1 positional argument but 2 were given"

### ISSUE THREAD

**Issue by louisfh** [kitzeslab/opensoundscape#923]
This is an issue with wandb and ipython, not specifically opensoundscape. But I am posting it here so we can:
1. Consider updating wandb dependency to fix the issue.
2. Ensure anyone else who runs into the issue using opensoundscape has documentation.

After running `wandb.login`, any cell executed in a jupyter notebook results in the following error.

```
TypeError                                 Traceback (most recent call last)
TypeError: _WandbInit._resume_backend() takes 1 positional argument but 2 were given
Error in callback <bound method _WandbInit._pause_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7fcc087ff400>> (for post_run_cell), with arguments args (<ExecutionResult object at 7fcc19293e20, execution_count=3 error_before_exec=None error_in_exec=None info=<ExecutionInfo object at 7fcc19293f10, raw_cell="2+2" store_history=True silent=False shell_futures=True cell_id=vscode-notebook-cell:Untitled-1.ipynb?jupyter-notebook#X10sdW50aXRsZWQ%3D> result=4>,),kwargs {}:
```

This appears to be a wandb issue caused in versions of `ipython` `>8.16.1`. See: https://github.com/wandb/wandb/issues/6546 

A workaround is to:
`pip install ipython==8.16.1`

This issue is apparently fixed in wandb  `v0.16.0`.

**Comment by louisfh** [comment]
@sammlapp Do you know how we've ended up with a <0.14.0 requirement for wandb in our pip distribution (see the PKG-INFO file in our pip source gz: https://pypi.org/project/opensoundscape/#files)

Seems a mystery to me, it's not specified in our `pyproject.toml`

**Comment by sammlapp** [comment]
nope not sure why. I think upgrading the dependency sounds good, we'll see if it breaks anything

**Comment by sammlapp** [comment]
@louisfh maybe we can close this, wandb version is now >=0.17. Does the error still occur anywhere?
