### ISSUE TITLE
revisit choice of default annotation column in BoxedAnnotations.from_raven_files

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#936]
using the 8th column is quite fragile. We could make the argument required, or could check for the default column names of both Raven and Raven Lite as the default behavior

**Comment by syunkova** [comment]
Is there a default common name? I thought Raven makes it blank if you don't input one, but I could be wrong about this

**Comment by sammlapp** [comment]
for now we'll just remove the default but allow both arguments (column position and name)
