### ISSUE TITLE
spectrum estimation 'wrong'

### ISSUE THREAD

**Issue by WMXZ-EU** [kitzeslab/opensoundscape#947]
in audio.spectrum   you have  fft = 2.0 / N * fft[0 : int(N / 2)].
this is correct for positive frequencies (index>0), but the DC term (index=0) must not be multiplied by 2.0

**Comment by sammlapp** [comment]
Thanks for pointing this out. We’ll address it soon. @WMXZ-EU could you provide a reference or derivation for this?

**Comment by WMXZ-EU** [comment]
Explanation is easy : FFT gives you DC, positive frequency bins, negative frequency bins. You wanted to remove negative  freqency bins  and in order to  maintain overall energy, you double the positive frequency bins.  Similar procedure applies to what is called 'analytical' extension of a real valued time series. Normally if the mean of the time series is 0, this doubling of the DC does not matter, but .... 
Hope this explanation is sufficient. 
But better verify my statement: generate time series with DC offset, obtain spectrum, estimate energy  (sum squared) of spectrum and time series and compare. They should be equal.

**Comment by sammlapp** [comment]
In the case of an even number of FFT bins, I think the sr/2 component of the FFT should also not be scaled by 2

Similar to 
https://github.com/librosa/librosa/blob/8dae20c66353190749486abf6b332d93c4ab2b46/librosa/feature/spectral.py#L896-L904

**Comment by WMXZ-EU** [comment]
Yes, DC and Nyquist frequency only appear once and should not be scaled by 2.

**Comment by sammlapp** [comment]
@WMXZ-EU I tried implementing your suggested check, but don't get equivalent power for the energy of the spectrum and time series. I think this is because in the FFT you can preserve either amplitude or power, and in scaling by 1/N we are choosing to preserve amplitude. However, I don't have a great grasp on this. 

Nonetheless, I think the change to the DC and Nyquist frequencies is correct. Would you like to review the PR?
https://github.com/kitzeslab/opensoundscape/pull/989

**Comment by sammlapp** [comment]
After investigating fft a bit more, I realized we might want to use an average of a sliding window stft to compute the spectrum. IE we could call https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.ShortTimeFFT.html#scipy.signal.ShortTimeFFT 
then take a time average. In this stfft implementation, passing fftmode='onesided2X' produces the output requested in this issue. We can make that the default behavior. For choosing a default of power vs magnitude, we can use magnitude as default, to match default in Spectrogram.from_audio().

We can expose all arguments to the user (**kwargs), including whether to get power spectral density (FFT**2 / N) or magnitude scaling (FFT/N).

**Comment by sammlapp** [comment]
since the error initially described is fixed in #fbab5d2, I'm going to leave this open for future exploration but remove #bug label

**Comment by sammlapp** [comment]
moved the remaining feature request/ update to #991, we can close this bug report once #989 is merged to master

**Comment by sammlapp** [comment]
Defaults for scipy.signal.ShortTimeFFT.spectrogram will produce slightly different time bins than scipy.signal.spectrogram, I'm not sure if we should just go with the defaults. Also, our usage of default `mode` arg (which defaults to  'psd') with `scaling=spectrum` seems to be an "invalid" combination that is not supported by `scipy.signal.ShortTimeFFT.spectrogram`. Lack of clear documentation of the old scipy.signal.spectrogram made it difficult to use the function correctly. 

we could also consider switching to torchaudio.transforms.spectrogram, which supports GPU acceleration. However, torchaudio API currently doesn't have a way to get frequency and time arrays corresponding to the spectrogram.
