### ISSUE TITLE
Tutorial showing best practice for saving models to use in later opso versions

### ISSUE THREAD

**Issue by louisfh** [kitzeslab/opensoundscape#965]
The documentation mentions using `model.save_torch_dict` and `CNN.from_torch_dict` to save and load model weights between opensoundscape versions, but there's no tutorial. I think it would be helpful to have a tutorial showing this.

e.g. something like
```
# save the model
model.save_torch_dict...
# load the model
CNN.from_torch_dict...

# recreate the preprocessor, make sure the settings are the same as in the old version!
hop_size = 256
window_length = 512
preprocessor = ....
```

**Comment by sammlapp** [comment]
I think this will be resolved by the implementation of preprocessor to/from dict as the default  behavior of model.save() (currently in `lightning` branch)
