### ISSUE TITLE
Use logged spectrograms

### ISSUE THREAD

**Issue by rhine3** [kitzeslab/opensoundscape#97]
By default, when spectrograms are generated, take the log of the amplitude values. This should result in a spectrogram that is comparable to spectrograms generated by popular audio analysis softwares (e.g., Raven & Audacity). It may also reduce the effect of "outlier" regions that are extremely loud.

Also add a config option to use the linear values instead (current behavior). Otherwise, config options related to amplitude will remain the same:
* `db_sparse_thresh_percent = 1.0` will remain the same, as we will still discard the lowest 1% of points
* `decibel_threshold = -100.0` will remain the same. The conversion to log will (likely) happen after this filter. Note that the amplitudes are in positive units of V^2; the decibel filter works by converting these values to decibels, applying the decibel threshold, then converting the decibels back into V^2.

**Comment by rhine3** [comment]
Also ensure that viewed spectrograms are logged as well.

**Comment by chiroptical** [comment]
@rhine3 This is already done right?
