### ISSUE TITLE
consider using Pytorch Lightning

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#978]
CNN would subclass LightningModule, which has things like automatic saving/loading of many of the attributes we save/load. Also implements higher level API similar to CNN in some ways

**Comment by sammlapp** [comment]
I refactored the machine learning modules so that both Lightning and pure PyTorch are supported. (`lightning` branch). Shared functionality is in a single class, opensoundscape.ml.cnn.SpectrogramModule. Separate module `ml.lightning` implements a subclass of LightningModule that has an API for using Lightning's Trainer for training and inference

**Comment by paulpeyret-biophonia** [comment]
Thanks for this update @sammlapp.

To follow up this thread #1026, I tested the `lightning` branch and managed to log metrics using MLFlow logger. 😃 

Strangly, even though I am not using wandb, I still get some warning of tmp wandb directories being cleaned up under the hood suggesting that some wandb options may still be running ?
`ResourceWarning: Implicitly cleaning up <TemporaryDirectory 'C:\\Users\\Username\\AppData\\Local\\Temp\\tmphgjkwwybwandb-media'`

I see that the model checkpoints are saved properly but I didn't manage to reload a model that embeds the inference dataloader (only get the weights) and opensoundscape.ml.cnn.load_model() doesn't work here.
I guess the load method is not implemented yet for the lightning flavor of OPSO?

Please let me know if there is new updates, I'd be glad to help with further testing.

**Comment by sammlapp** [comment]
Ok thanks for checking it out! I do think I still need to implement i/o for the lightning module model saving/loading. And I'll look into that strange wandb behavior.

**Comment by sammlapp** [comment]
hey @paulpeyret-biophonia, I've implemented the model saving/loading and also the preprocessor saving/loading (which now happens by default for preprocessor belonging to the main model classes CNN or LightningSpectrogramModule when you save and load them). We'll merge this to all to `develop` soon, for now its still in the `lightning` branch.
