### ISSUE TITLE
matplotlib not being released when saving spectrogram to file

### ISSUE THREAD

**Issue by AdamVarley30** [kitzeslab/opensoundscape#987]
Great package!!!

Doesn't warrant a PR from me.  Just need to close plt object otherwise you run into memory issues with loops

Spectrogram.py line 446

 if fname:
            plt.savefig(fname)

add plt.close()

**Comment by sammlapp** [comment]
Thanks for pointing this out. I'm unclear on when plt.close() needs to be called. For instance, if plt.show() is called, should plt.close() still be called afterwards? (applies to other places in the code as well such as signal_processing.py L373

**Comment by AdamVarley30** [comment]
I'm not exactly sure if it specifically required, but I think it is good practice. I'm not an expert, but I think it might still hold some reference to the file connection and this will probably be maintained until the session ends. So can be problematic if lots of call are made. I'm sure someone with more experience in matplotlib would be better to comment :-)
