### ISSUE TITLE
from_raven_files function error

### ISSUE THREAD

**Issue by w-out** [kitzeslab/opensoundscape#993]
When using the from_raven_files function, it appears to only read the first character of the filename string.

`annotations = BoxedAnnotations.from_raven_files(row['raven_file'], annotation_column_name = 'annotation')
`
Within a for loop, this code gives the following error.

_IsADirectoryError: [Errno 21] Is a directory: '/'_

The following has already been checked:
- The input row['raven_file'] within the for loop does correspond to a specific raven selection table file. If we add a print(row['raven_file']) within the loop, it returns the entire string.
- The function only seems to read the first character, since if we replace the filenames with another string, it also only reads the first character.
- The external harddrive is mounted correctly.
- I'm working in an opensoundscape environment and other opensoundscape functions perform as expected.

**Comment by sammlapp** [comment]
The function expects a list (or other iterable) of file paths and you are passing a string. As a result it is iterating the string resulting in each character being used as a path. Just put [] around the file path. We will improve the error message to make it more interpretable.

**Comment by sammlapp** [comment]
I decided to modify the API to allow passing a single path (string or pathlib.Path), which is converted internally into a list with a single item.
